### ISSUE TITLE
Simple web lobby implementation

### ISSUE THREAD

**Issue by scally** [nicolodavis/boardgame.io#197]
As a followup to #189 , we will need a simple implementation of a web lobby utilizing the new API

> No real persistence. Just have the user fill in their username (no password) and have some UI to create games and allow others to join. This will create a good base for people that want to add OAuth or something else on top of that.

**Comment by MrRhodes** [comment]
Has anyone picked this up ?

**Comment by nicolodavis** [comment]
I'm not sure if @scally posted this as a way of documenting what he would work on next, or if this is open. Let's check with him.

**Comment by nicolodavis** [comment]
I'm a big fan of minimalist (mostly text) UI that provides hooks for people to customize if they want a different look and feel. Here are some thoughts on what it could look / behave like:

- there is a text field somewhere on the page (top right perhaps?) that allows you to enter your handle name
- the middle area should probably have a list of currently active games (separated into different tabs like OPEN / RUNNING) displayed in a tabular format
- any OPEN game should have a "join" button next to any player seat that isn't currently taken
- a full game should have a link that takes you to the game page where you actually play

We can probably store player credentials (required to join a game) in either cookies or local storage.

**Comment by nicolodavis** [comment]
We could also actually start even smaller:
1. Just a simple "Create Game" button at the center of the page. This just creates a game with a URL that you can share with your friends.
2. The second page just contains "Join Game" buttons.
3. Once everyone is in, the game starts.

**Comment by amitport** [comment]
added an Angular initial lobby example in
https://github.com/turn-based/boardgame.io-angular/tree/master/src/app/examples/lobby

The most obvious gap exemplified this implementation is that there is missing server APIs for:
1 game session metadata- Specifically, numOfPlayers + current players metadata (index id and name).
2 getting all those game sessions for the lobby (possibly with filter parameters like gametype)

**Comment by nicolodavis** [comment]
Thanks for uncovering those, Amit! I'll add them to the roadmap. Feel free to also send me a PR if you have time to work on these yourself.

**Comment by francoijs** [comment]
A few things may still be missing to finish the initial lobby implementation:
- _numPlayers of a new game instance_: each child of class Game could provide 2 properties minNumPlayers and maxNumPlayers ; the actual numPlayers of a game instance will be chosen inside those boundaries at creation in the lobby 
- _ability for server to notify lobbies that a player seat has been taken/released_
- _ability for server to notify lobbies that a game has changed state_ (OPEN/RUNNING/OVER)
-> ultimately it could be implemented though a redux store for each game instance? Before that we could simply make the lobby poll the server periodically (using the present RESTful API) to detect a change of state for the game instances

**Comment by chonghorizons** [comment]
I'm new to boardgame.io and interested in the lobby feature. I found and read through this code that seems to do a robust job of creating game lobbies and managing sockets:

https://github.com/falconscript/gamelobby

I'm going to read through the above items of this issue #197 (including amitport's Angular implementation) and see if I can contribute to this feature. I'm new, so no promises on my ability to make a good contribution, but I'll try!

**Comment by francoijs** [comment]
@chonghorizons we have another primitive lobby implementation in #256 if you want to have a look.

**Comment by francoijs** [comment]
PR #294 ready for review!

**Comment by flamecoals** [comment]
PR #294 was merged, do we have any examples using it? If not, I think I can help adding one

**Comment by flamecoals** [comment]
We do! But I am getting an error:
![image](https://user-images.githubusercontent.com/1034631/51446215-f4fb3f00-1cdc-11e9-8642-8295e52a4177.png)

I will try to debug.

**Comment by flamecoals** [comment]
Ok, sorry, this error seems to be happening only in my ChromeOS because of this bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=848127

They only foward *some* ports by default 8000 is one but 8001 is not, and if I try to use the domain instead I get a CORS because of the lack of HTTPS :(

**Comment by nicolodavis** [comment]
Looks like you need #343.

**Comment by nicolodavis** [comment]
Closing this in favor of #354
