### ISSUE TITLE
React-Native Client: Error with Android

### ISSUE THREAD

**Issue by chrisheninger** [nicolodavis/boardgame.io#213]
Hi @nicolodavis! 👋

I've been working on a React-Native version of matchimals.fun over the past few weeks! In the process, I discovered a bug that we've ran into before.

When we were initially writing the React-Native Client (#128)– we found that for some strange reason `for...of` loops weren't getting transpiled properly– and while iOS is okay– Android doesn't know how to handle them.

<img width="603" alt="screen shot 2018-06-04 at 8 57 35 pm" src="https://user-images.githubusercontent.com/5051745/40954843-4dcf9c86-683b-11e8-8afd-cac810b4f182.png">

It looks like these lines didn't exist when we first made the RN Client but need to be changed to regular `for` loops: 
https://github.com/google/boardgame.io/blob/master/src/core/events.js#L28
https://github.com/google/boardgame.io/blob/master/src/core/events.js#L42

I can make the updates and submit a PR if that sounds like an okay change to make.

**Comment by nicolodavis** [comment]
Sure!

**Comment by nicolodavis** [comment]
Great! I'll start fixing the for of loops anyway. Is there anything else we need to fix in the short-term or is your workaround a good enough solution for you?

**Comment by nicolodavis** [comment]
I think this should no longer be a problem with newer versions of `create-react-native-app`.  Feel free to re-open if there is anything we should be doing on our end.
