### ISSUE TITLE
Can't run server "can't read properties 'name' of undefined"

### ISSUE THREAD

**Issue by lusiaskolonie** [nicolodavis/boardgame.io#283]
Can't run server when I try to run multiplayer script

![screen shot 2018-10-12 at 11 36 59 am](https://user-images.githubusercontent.com/8683941/46848301-3f823b00-ce13-11e8-8a4f-0c76f1046660.png)

**Comment by nicolodavis** [comment]
You probably didn't pass valid objects to the games option. I can improve the error message to reflect that.

Send us a message on Gitter if this doesn't resolve your problem.

**Comment by lusiaskolonie** [comment]
Can you send a valid multiplayer example code to me? 
Because I try to follow your tutorials in documents. but can't run.

**Comment by nicolodavis** [comment]
Will do. I'm also in the process of updating the documentation right now, so let me finish that up and I'll add a link to the entire code on the page itself.

**Comment by nicolodavis** [comment]
@lusiaskolonie I've updated the multiplayer documentation (including links to the code): http://boardgame.io/#/multiplayer

Let me know if this is clearer (I'd love to know if there is anything else we can fix here).

**Comment by lusiaskolonie** [comment]
@nicolodavis Thank you, I'll send feedback when I try it again.
