### ISSUE TITLE
Mongo Warning

### ISSUE THREAD

**Issue by RGBKnights** [nicolodavis/boardgame.io#284]
I get the following warning when integrating with Mongo.

(node:788) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect. 

To fix this I needed to add { useNewUrlParser: true } to the connect() method of the mongo client. 
Like so:
```
var c = await this.client.connect(this.url, { useNewUrlParser: true });
```

I am not sure if you should make this change for all moving forward or to add a new option to the Mongo class called useNewUrlParser and pass that long to the connect() method.

**Comment by nicolodavis** [comment]
We should probably make the change for all. Thanks for the report. Do you have time to send me a PR for this?

**Comment by RGBKnights** [comment]
Done.

**Comment by nicolodavis** [comment]
Thanks @RGBKnights!
