### ISSUE TITLE
Reduce API Surface: Hide Game()?

### ISSUE THREAD

**Issue by Izhaki** [nicolodavis/boardgame.io#288]
1. There might be a good reason for this which is beyond me.
2. Yes, it's a breaking change!

But still...

---
From the docs:
```
import { Client } from 'boardgame.io/react';
import { Game } from 'boardgame.io/core';

const TicTacToe = Game({
  setup: () => ({ cells: Array(9).fill(null) }),
  // ...
});

const App = Client({ game: TicTacToe });
```
Why do we need to import `Game` and call it?

Why not just:

```
import { Client } from 'boardgame.io/react';

const TicTacToe = {
  setup: () => ({ cells: Array(9).fill(null) }),
  // ...
);

const App = Client({ game: TicTacToe });
```

And have `Client` invoking `Game`?

I've looked throughout the docs and couldn't find why not doing it this way.

**Comment by nicolodavis** [comment]
This is a good idea.  `Game` does do some initialization work, but `Client` and `Server` can just call `Game` internally and it would be a pretty simple change to implement.

Do you have time to make a PR for this?

**Comment by Izhaki** [comment]
Guess I could.

How do you envision it? Mainly:

- Shall `game` be allowed to be either the result of `Game()` or just plain object (as determined by looking at the `processMove` prop)?
- Deprecation message if `Game()` was called?

**Comment by nicolodavis** [comment]
This was fixed as part of the "phases-overhaul" effort.
