### ISSUE TITLE
Mongo - Round 2

### ISSUE THREAD

**Issue by RGBKnights** [nicolodavis/boardgame.io#289]
After doing some more testing and reviewing the logs, it seems there is another method that needs upgrading so I figured I should do that one to complete the work.

I also added an additional env variable for MONGO_DATABASE as it stands if you try and use MONGO_URI currently it will fail stating database 'bgio' dose not exist.

**Comment by nicolodavis** [comment]
Thanks a lot @RGBKnights! Will take a look.

**Comment by RGBKnights** [comment]
Did the build not happen correct because I updated to 0.26.3 but I do not see the changes in the server.js in the dist.

**Comment by nicolodavis** [comment]
It's not in `0.26.3`. It will be in the next release.
