### ISSUE TITLE
server sync status indicator

### ISSUE THREAD

**Issue by flungloaf** [nicolodavis/boardgame.io#297]
Is there a way of doing that? When i am starting my game, my board component receives props from the single player game mode, then `isConnected` turns to `true` and after that i am actually receiving the state of the game from the server. This results in flickering of the rendered board. Checking for `stateId` doesn't really work for games that have just started. Am i missing something?

**Comment by nicolodavis** [comment]
There isn't a way to do this at the moment unfortunately. I think a boolean prop on the client indicating that the sync with the game master has completed would be good to have. That way you can display 'loading...' or something until the server gets back with the initial state.

**Comment by flungloaf** [comment]
@nicolodavis Do you have an idea on how this should be implemented? I'm willing to work on it

**Comment by nicolodavis** [comment]
Hey @flungloaf.  This should be as simple as:

1. Adding a new field to this [class](https://github.com/nicolodavis/boardgame.io/blob/master/src/client/client.js#L78) that is a boolean initially set to false.

2. Set it to true [here](https://github.com/nicolodavis/boardgame.io/blob/master/src/client/client.js#L177). This code is called when the server returns with a sync.

3. Return this field in [getState](https://github.com/nicolodavis/boardgame.io/blob/master/src/client/client.js#L255).

**Comment by flungloaf** [comment]
Opened #307

**Comment by nicolodavis** [comment]
Thanks for implementing this!
