### ISSUE TITLE
optimisticUpdate cleanup

### ISSUE THREAD

**Issue by nicolodavis** [nicolodavis/boardgame.io#298]
The `optimisticUpdate` logic currently works as follows:
1. We execute the move on the client (always).
2. We check if some randomness related code was executed.
3. We then check if the user-provided `optimisticUpdate` function returned `true`.

Relevant code: [link](https://github.com/nicolodavis/boardgame.io/blob/master/src/core/reducer.js#L250)

If either [2] or [3] are true, the move result is discarded.

The problem here is that the move is always executed (on the client) in the first place. This can cause errors for moves that rely on secret state because they don't have access to all the data. We need to execute the move in order to check [2], but don't need to for [3].

The current workaround is to defensively program the move such that it checks for the presence of necessary data before transforming the state.

Proposed fixes:
- Check `optimisticUpdate` early and don't execute the move if it returns true.
- Split the randomness check out of `optimisticUpdate` and execute it after the move.

Nice to have:
- Create an option that accepts a list of moves to disable on the client that complements `optimisticUpdate`.

**Comment by nicolodavis** [comment]
Fixed in the phases-overhaul branch.  Will be in an upcoming release.

**Comment by delucis** [comment]
Closing this now that moves can use the long-form syntax and `client: false` and plugins can declare a `noClient` method.
