### ISSUE TITLE
Support more general game logic

### ISSUE THREAD

**Issue by kaoet** [nicolodavis/boardgame.io#299]
The phase and turn model is great. However, it is limited to a two-level structure: a game has many phases, each phase has many turns. Although we can control the condition to end the turn or phase, we cannot define a phase-in-trun-in-phase or turn-in-turn-in-phase game logic.

Consider the following game. The game has two phases. In the first phase, each player choose some cards from the deck. In the second phase, each player requests all other players to give him/herself a card. Although this game is not interesting at all, but it has a turn-in-turn-in-phase logic:

* Phase 1
  * Player A's turn to choose cards.
  * Player B's turn to choose cards.
  * ...
* Phase 2
  * Player A's turn to receive cards.
    * Player B's turn to give A a card.
    * Player C's turn to give A a card.
    * ...
  * Player B's turn to receive cards.
    * Player A's turn to give B a card.
    * Player C's turn to give B a card.
    * ...
  * ...

**Comment by nicolodavis** [comment]
You can have turns within turns and phases within turns. The example you described is doable with the current set of primitives. Let me get back to you with how to do it when I'm at a computer.

**Comment by nicolodavis** [comment]
The key to implementing a turn-in-turn is to use [`actionPlayers`](https://boardgame.io/#/turn-order). `currentPlayer` owns the turn, and `actionPlayers` can make moves in the current turn. So in your example, you want something like this:

- Phase 1
  - currentPlayer = 'A' actionPlayers = ['A']
  - currentPlayer = 'B' actionPlayers = ['B']

- Phase 2
  - currentPlayer = 'A' actionPlayers = ['B']
  - currentPlayer = 'A' actionPlayers = ['C']
  - ...
  - currentPlayer = 'B' actionPlayers = ['A']
  - currentPlayer = 'B' actionPlayers = ['C']
  - ...

**Comment by nicolodavis** [comment]
At the moment the only way to modify `actionPlayers` is via the `setActionPlayers` event. I'm working on a change to integrate this more closely with the turn-order code so most of these patterns will be available as standard turn orders that you can use off-the-shelf.

**Comment by nicolodavis** [comment]
This is now done.  Let me know if we're missing anything.
