### ISSUE TITLE
Phases doesnt work when switch to multiplayer 

### ISSUE THREAD

**Issue by pociej** [nicolodavis/boardgame.io#301]
Im jumped on multiplayer to be able to use storage ( btw dont you think its strange that even in single player game if you want to have db storage you have to use multiplayer option ? ). 
My game works just fine as single player : 
```
const App = Client({
  game: Transition,
  board: TransitionBoard,
  numPlayers: 1,
  currentPlayer: "1",
});
```
but once i change few lines to work with multiplayer : 

```
const MultiPlayerClient = Client({
  game: Transition,
  board: TransitionBoard,
  numPlayers: 1,
  currentPlayer: "1",
  multiplayer: {
   //Just temp to check if multiplayer option works, mongo storage will be connected. 
    local: true
  }
});

const App = () => (
  <div>
    <MultiPlayerClient playerID="0" />
  </div>
);
```

My game is stuck to phase 1, neither `endPhaseIf` nor `ctx.events.endPhase();` works,`endPhaseIf` is not called at all after G update on move. What could be that?

**Comment by nicolodavis** [comment]
Any minimal example that reproduces the problem will do.

**Comment by pociej** [comment]
@nicolodavis its strange i tried to reproduce and im unable but in orginal repo ( i made it public temporary) problem persists. Here it is if you could be so polite and take a look https://bitbucket.org/planszowki/change_management/src/0c0de55cf9e25da8bf4b55bb2dc936e39d796639/imports/ui/main.jsx?at=master&fileviewer=file-view-default.

**Comment by nicolodavis** [comment]
You're running an old version of boardgame.io (which if I recall correctly contained a bug that is similar to what you're describing). Can you upgrade to the latest version and let me know if that fixes it?

**Comment by pociej** [comment]
Yes thx a lot, update helps for this, but unfortunately it produces another issue.  In case of single player game with multiplayer option set, each single move fires twice. Im going to check if i can reproduce it out of my app.

**Comment by nicolodavis** [comment]
About moves firing twice, I would expect the move to fire once on the client and once on the [master](https://boardgame.io/#/multiplayer?id=clients-and-masters), which is also running on the browser in "local multiplayer" mode. Is this what you are observing?

**Comment by pociej** [comment]
When i put `multiplayer : { server : 'loalhost:3010' }` then i works normally, so you might be right its rerun on master, but look, every move from my game defined like this :  
```
Game({
  setup : ctx => {
    ....
  }, 
 moves : {
   a : (G,ctx,name) => { ... }
   b : (G,ctx,name) => { ... }
 }
}}
``` 
When i call it from board component by : 
```this.props.moves.a()```  

is called twice, and as its not idempotent `G` state is updated twice, and on my board i see effect of double move rendered. Is it expected behaviour? Isn't it make `{ multiplayer : {local : true} }`

**Comment by nicolodavis** [comment]
You should definitely not see your `G` object updated twice.  The client and master maintain two distinct game objects that are updated independently.

I can take a closer look later.  In the meantime, a minimal example that demonstrates the problem would be quite helpful (if you have the time).

**Comment by pociej** [comment]
Wow i see 0.27.0 is released i updated to this version and now orginal issue is back. 
So all moves are called once as should, but phase ending doesn't work any more with multiplayer.

**Comment by pociej** [comment]
Ok i see where is trap with double calling : 
if you return from move function modified version then everything works, but if in function body you modify G object like `G.myArray.push()` then two calls ends up with double push. Its still a bit counter intuitive behaviour. for me but now i understand and i fixed.  Sorry, and thx a lot for your help.

**Comment by nicolodavis** [comment]
Ah glad this is resolved. I'm actually planning to bundle in Immer in a future release which will avoid this problem https://github.com/mweststrate/immer.

So, with 0.27.0 does everything work correctly? I'll close this issue if so. Feel free to reopen if there is anything else we should fix right now.
