### ISSUE TITLE
onMove....

### ISSUE THREAD

**Issue by pociej** [nicolodavis/boardgame.io#309]
... is registerable on both flow and phase level but phase level has priority. I don't think its intentional why don't have array on `onMove` callbacks and run them one after another? In my feeling it should have more middlewareish nature than what we have now.

**Comment by nicolodavis** [comment]
Phase-level attributes always override their global equivalents.  This is by design (and also how all the other attributes like turn orders work as well).

We do have a middleware-like solution for moves now.  Take a look at the [Plugin API](https://boardgame.io/#/plugins).
