### ISSUE TITLE
onGameEnd...

### ISSUE THREAD

**Issue by pociej** [nicolodavis/boardgame.io#310]
... seems to be missing. When running in multiplayer mode `endGameIf` is called only server side. Isn't it natural to provide `onGameEnd` option ?

**Comment by nicolodavis** [comment]
`onGameBegin` and `onGameEnd` are features that I've been meaning to add but just haven't had time to get to.

**Comment by nicolodavis** [comment]
That would be great!

**Comment by JameyCalbreze** [comment]
What's the status on this feature? This seems like a good place for me to learn this engine.

**Comment by nicolodavis** [comment]
I'm already on this as part of the API redesign (see the phases-overhaul branch). Should be out in a week or so.

**Comment by jasonharrison** [comment]
@nicolodavis Was this added?

**Comment by nicolodavis** [comment]
Not yet, but it's going to be in the `phases-overhaul` branch as `onBegin / onEnd`.

**Comment by delucis** [comment]
Done in d84e6af69533f1c0e8eed76d19ba5b8172eb2ea0
