### ISSUE TITLE
Issue sharing Game object with server

### ISSUE THREAD

**Issue by tomdixon** [nicolodavis/boardgame.io#312]
I have been following through the tutorial and guides in order to get an idea of how the engine works. However, I ran into an issue when converting the example Tic Tac Toe game to multiplayer with a remote server. I modified the Game file to be node friendly:

```
module.exports = { TicTacToe };
```

However I now get an error when running the game in the browser:

```
TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
```

As far as I can tell this is a known restriction with Webpack (I'm using `create-react-app`). Whatever I do I can't seem to create a Game object that I can use both for the server and for the React Client, and I obviously want to avoid having to duplicate it.

Any ideas for a way around this, or will I have to look at ditching Webpack and going a pure node route perhaps?

Thanks!

**Comment by tomdixon** [comment]
Hey @nicolodavis thanks for the quick reply. I tried the CodeSandbox link which does indeed work perfectly for me. 

I noticed it's using `react-scripts` `1.1.4` and my brand new `create-react-app` is using `2.1.1`. If I update your example to `2.1.1` then the problems start to appear. Initially it won't compile as it doesn't like importing TicTacToe in `index.js`:

```
Attempted import error: 'TicTacToe' is not exported from './game'.
```

If you swap this for a `require` instead:

```
const TicTacToe = require('./game').TicTacToe
```

then you get the original error I reported.

Seems like newer Webpack versions don't like you mixing and matching the two styles of module import/export? For now I can downgrade in my project, any thoughts on a solution going forwards though?

**Comment by nicolodavis** [comment]
My recommendation then would be to convert `game.js` to an ES module (only use import / export) and then use something like [esm](https://github.com/standard-things/esm) to make it work on Node.

The following should work (without needing to change anything in `server.js`):
$ npm i esm
$ node -r esm src/server

The alternative is to use a transpiler for the server code as well.

**Comment by nicolodavis** [comment]
I'll update the docs and CodeSandbox to reflect this if it works well.

**Comment by tomdixon** [comment]
Thanks for the tip, I wasn't aware of `esm` - that worked nicely!

**Comment by nicolodavis** [comment]
I've updated the [docs](https://boardgame.io/#/multiplayer).  Let me know (for the benefit of others) if it's clear or if any steps could be explained better.

Thanks for reporting this!

**Comment by tomdixon** [comment]
Yep - that looks clear to me. Thanks!
