### ISSUE TITLE
ctx.currentPlayer when only 1 player

### ISSUE THREAD

**Issue by philihp** [nicolodavis/boardgame.io#313]
When I create a game with only one player, `ctx.currentPlayer` is undefined, however `G.players` has a hash with a key of '0' for the first player.

Is this a bug, or is this intentional?

**Comment by nicolodavis** [comment]
Definitely a bug. Will take a look.

**Comment by philihp** [comment]
Hmm, actually might have to do with some of my custom turn orders (warning: [it's ugly](https://github.com/philihp/fields-of-arle/blob/master/src/game.js#L29-L44)).

Thanks for checking!
