### ISSUE TITLE
Passing arbitrary data to game setup

### ISSUE THREAD

**Issue by flungloaf** [nicolodavis/boardgame.io#314]
I saw this mentioned in #207 and would like to submit a PR on it.  My understanding is that `/games/:name/create` endpoint accepts a `data` (or whatever we call it) field and passes it to  `CreateGameReducer`, which calls `game.setup` with it. Is this flow what you had in mind? @nicolodavis

**Comment by nicolodavis** [comment]
Yep, exactly.  Thanks for taking this on!

**Comment by flungloaf** [comment]
Created #315

**Comment by nicolodavis** [comment]
Merged.
