### ISSUE TITLE
Minor bug in game leave API

### ISSUE THREAD

**Issue by prvnsmpth** [nicolodavis/boardgame.io#325]
In `src/server/api.js` in the `leave` API handler (line 174), the following check is made:

`playerCredentials !== gameMetadata.players[playerID].playerCredentials`

The actual property name in gameMetadata is `credentials` and not `playerCredentials`, and so this check always fails, and the API call returns a 403.

**Comment by francoijs** [comment]
Absolutely correct. This is fixed in the PR #294 but not yet merged into master. If everybody agree I can  cherry-pick the fix in a separate PR so that it is merged sooner.

**Comment by francoijs** [comment]
fix in PR #326

**Comment by nicolodavis** [comment]
Thanks for the fix @francoijs!
