### ISSUE TITLE
Koa server and transport layer port

### ISSUE THREAD

**Issue by lime-cake** [nicolodavis/boardgame.io#330]
The Authentication server (Koa) and transport layer (socket.io) use different port, respectively port and port+1. Where port is passed as a param when creating 'Server'

This is problematic for deploying to most hosting popular service, such as Heroku, which require using a single port passed as system variable.

**Comment by prvnsmpth** [comment]
Second this, I noticed the same issue when trying to deploy to Heroku. MIght be better to allow specifying both the game server and api ports explicitly.

**Comment by lehaSVV2009** [comment]
@nicolodavis I'm not well aware of the server architecture here, but does it make sense to combine websocket and http api to a single koa instance? It looks like adding env variable like `process.env.API_PORT` will not simplify server deployment to heroku or smth similar.. P.S. I'll probably try to do that for my game app, so I can give a feedback later if it works ok or not (or if new version breaks backward compatibility..)

**Comment by lehaSVV2009** [comment]
Kind of first working attempt is here - https://github.com/lehaSVV2009/boardgame.io/commit/47be648f045d505aa1b2e6373cfc411b4beefc86. But need to think if it might be improved, cover by tests, check that it doesn't break old versions and if all is good create a PR.
Client example - https://github.com/lehaSVV2009/tic-tac-toe-client
Server (deployed on heroku) example - https://github.com/lehaSVV2009/tic-tac-toe-server
