### ISSUE TITLE
React Native: Expo SDK Version Out Of Date

### ISSUE THREAD

**Issue by blunket** [nicolodavis/boardgame.io#336]
## EDIT:

I just realized my error below, I was trying to use `expo start` where I should've been using `npm start`.

However, the SDK version is outdated, so the example app is still not working as expected.

I've renamed this issue but I'll keep my below post too.

---
### old post:
The given example for react-native doesn't work with expo as expected. It is possibly just **very** out of date? I notice the SDK version in app.json is old.

reproduction: 

```
git clone git@github.com:nicolodavis/boardgame.io.git
cd boardgame.io/examples/react-native
npm install
expo start
```

Then, try to open the project in Expo on my phone. If it makes a difference, I'm on an Android phone (OnePlus 6).

I get first:
```
[20:10:19] Unable to resolve "../../App" from "node_modules/expo/AppEntry.js"
[20:10:19] Failed building JavaScript bundle.
```

So, I tried renaming app.js to App.js:
 ```
mv app.js App.js
```

The error then changes:
```
[20:12:49] Unable to resolve "../../packages/react-native" from "App.js"
[20:12:49] Failed building JavaScript bundle.
```

Not sure what to do anymore or if I'm doing something wrong.

**Comment by nicolodavis** [comment]
I haven't touched the React Native example for a while, so it is possible that it is just the case that it's out of date and needs some maintenance love.

Do you have time to to dig into this further and fix the example?  If not, I will get around to it after making some progress on my current TODO list.

**Comment by blunket** [comment]
Thank you very much for your reply @nicolodavis!

I can try to help out, but unfortunately I have no guarantee I'll be able to -- I'm sorry! I'm a complete beginner to both React and React-Native, I was going to use this library for my 2nd-ever project :) 

Hope someone else can work on this. Merely updating the SDK version in the app.json file doesn't fix it though.

**Comment by nicolodavis** [comment]
Sure, no worries!  Maybe you can just paste the error message that you're getting after updating the SDK and I'll try to poke around when I get the time?

**Comment by JasonTam** [comment]
Hellos, I'm also having similar issues.
I made the following changes (as per https://blog.expo.io/expo-sdk-v32-0-0-is-now-available-6b78f92a6c52):
```diff
diff --git a/examples/react-native/app.json b/examples/react-native/app.json
index 0811be3..a57d210 100644
--- a/examples/react-native/app.json
+++ b/examples/react-native/app.json
@@ -1,5 +1,5 @@
 {
   "expo": {
-    "sdkVersion": "25.0.0"
+    "sdkVersion": "32.0.0"
   }
 }
diff --git a/examples/react-native/package.json b/examples/react-native/package.json
index 7bc3bd9..e7d6b17 100644
--- a/examples/react-native/package.json
+++ b/examples/react-native/package.json
@@ -4,7 +4,7 @@
   "private": true,
   "devDependencies": {
     "babel-plugin-module-resolver": "^3.1.1",
-    "jest-expo": "25.0.0",
+    "jest-expo": "32.0.0",
     "react-native-scripts": "1.11.1",
     "react-test-renderer": "16.2.0"
   },
@@ -20,8 +20,8 @@
     "preset": "jest-expo"
   },
   "dependencies": {
-    "expo": "^25.0.0",
-    "react": "16.2.0",
-    "react-native": "0.52.0"
+    "expo": "^32.0.0",
+    "react": "16.5.0",
+    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"
   }
 }
```
Then `npm install`, and `npm start`
After that, it seems to hang on building the bundle:
```
21:56:26: ::ffff:192.168.1.139 - - [30/Jan/2019:02:56:26 +0000] "GET /onchange HTTP/1.1" - - "-" "okhttp/3.6.0"
21:56:27: ::ffff:192.168.1.139 - - [30/Jan/2019:02:56:27 +0000] "GET /onchange HTTP/1.1" - - "-" "okhttp/3.6.0"
21:57:02: Warning: You are using npm version 6.7.0. There may be bugs in this version, use it at your own risk. We recommend version 4.6.1.
21:57:02: ::ffff:192.168.1.139 - - [30/Jan/2019:02:57:02 +0000] "GET /node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&minify=false&hot=false&assetPlugin=/home/jason/tools/boardgame.io/examples/react-native/node_modules/expo/tools/hashAssetFiles HTTP/1.1" 200 - "-" "okhttp/3.6.0"
21:57:10: ::ffff:192.168.1.139 - - [30/Jan/2019:02:57:10 +0000] "GET /onchange HTTP/1.1" - - "-" "okhttp/3.6.0"
Building JavaScript bundle [                                                                                  ] 0%
```

**Comment by nicolodavis** [comment]
Took a look at this today and upgraded to the latest Expo version using the expo cli.  Need to figure out how to import the `package` directory from the root of the repo (which is outside the Expo project) now.

**Comment by nicolodavis** [comment]
@JasonTam Did you not run into the error that it cannot resolve `../../packages`?

**Comment by nicolodavis** [comment]
I've fixed the issue now.  Let me know if the examples work now.
