### ISSUE TITLE
Join API should stop giving out credentials for filled player slot with empty name

### ISSUE THREAD

**Issue by lime-cake** [nicolodavis/boardgame.io#337]
~~At the moment, anyone can POST to /games/{name}/{id}/join with arbitrary playerID, even if a player have already joined as that ID. This allows players to join a game, taking the slot of another player already playing.~~

~~Joining games shouldn't be allowed for slots already filled.~~

Edit: Not any player slot, but those with empty name.

If the player's name is empty, anyone can join with the playerID and steal said player's credentials.

**Comment by lime-cake** [comment]
#338 PR because it's like 1 line of code. Also because google's CLA now doesn't require me to find out where I live. Should I close this issue?

**Comment by delucis** [comment]
This should be fixed by febb1c082b454eff1554be2678dc295834fed778. It’s no longer possible to join a game with an empty string as the player name.
