### ISSUE TITLE
onPhaseBegin/turnOrder perhaps not working as intended

### ISSUE THREAD

**Issue by djMax** [nicolodavis/boardgame.io#339]
Here's the code from https://github.com/nicolodavis/boardgame.io/blob/133e23af5f0e1fdf5b73ede0e734195e4a1205fe/src/core/flow.js#L379

```
    let G = config.onPhaseBegin(state.G, state.ctx);
    let ctx = InitTurnOrderState(state.G, state.ctx, config.turnOrder);
```

So the problem here is that I modify the G state during onPhaseBegin. So shouldn't that G argument to initTurnOrderState be G and not state.G?

**Comment by nicolodavis** [comment]
Yes, this is a bug.

Thanks for the report! Will fix this (also happy to review a PR if someone else wants to take a stab).
