### ISSUE TITLE
Express support?

### ISSUE THREAD

**Issue by djMax** [nicolodavis/boardgame.io#340]
I would like to deploy a boardgame.io react app to heroku as part of an existing app built on express. I could move the existing express app over to koa I suppose, but even still the boardgame server is fairly monolithic so I'd have to figure out how to plumb in the React built static resources. Could it be broken up or documented in such a way that we can support other web server frameworks and running as part of a larger application?

**Comment by nicolodavis** [comment]
We've had multiple requests to make it even more monolithic (combine the API and socket servers into one koa app that serves on a single port).

I'm personally in the other camp that likes to separate everything. We should just provide a flag / options to allow both setups. This is already being worked on.

**Comment by nicolodavis** [comment]
I'll close this now that we have #343 (which should be merged soon).
