### ISSUE TITLE
Possible feature request: INVALID_TURN constant?

### ISSUE THREAD

**Issue by blunket** [nicolodavis/boardgame.io#344]
Currently my game client can call endTurn. However, I need to validate the turn one last time on the server-side in such a way that cannot easily be done on the client side *while* the turn is being made. I'd like to validate turns on both the client and server anyhow.

So after reading this: https://github.com/nicolodavis/boardgame.io/issues/91 ... It looks like the best solution (as of now) is to disable client-side endTurn calls, add an actual "endTurn" *move*, validate the turn _there_, and then call `endTurn` from the actual _Game_ instance.

I really like that I can return `INVALID_MOVE` from a move function. Is there some possibility to have like an `INVALID_TURN` constant that i can return from the `onTurnEnd` hook?

(For a clearer picture: in my game, capturing an enemy piece on a turn is mandatory if at all possible, similar to checkers; I need to check and make sure, at the end of the turn, that the player has made the mandatory captures)

**Comment by blunket** [comment]
This is probably not high priority. Just may be convenient. The behavior I'd like to implement is that if the turn is considered invalid, all moves in the turn will be undone so the player can retry. (probably not all games will want to undo everything though.)

**Comment by blunket** [comment]
Quick update on this:

Actually as it turns out, I get the following error whenever my game move functions return ANYTHING (in this case, i have them returning INVALID_MOVE)

![image](https://user-images.githubusercontent.com/17580512/51491067-d2b40080-1d72-11e9-9fd8-45240dd237ad.png)

**Comment by nicolodavis** [comment]
The error is because you're modifying `G` in the same function where you return `INVALID_MOVE`, which is not supported by Immer. You should either:
1. Modify G and not return anything, OR
2. Return the new value of G (or INVALID_MOVE) without mutating G.
but you can't do both.

I can see how this might be inconvenient. We should find a workaround.

**Comment by blunket** [comment]
Oh! Thank you for the tip!

**Comment by nicolodavis** [comment]
Great. Your feature requests and bug requests are quite helpful too, so keep them coming in as you notice issues!

**Comment by blunket** [comment]
Hey @nicolodavis.
Totally understandable for now, though I wonder how this will work with AI implementation given that it's not intended to be a valid move.

**Comment by nicolodavis** [comment]
Can you elaborate? A bot would never make invalid moves in the first place (i.e you would not have it end the turn before the condition has been fulfilled), so I'm not sure if we need this for AI purposes.

**Comment by blunket** [comment]
Oh, okay, I'm sorry! Thanks for explaining.
