### ISSUE TITLE
Player can undo during other player's turn

### ISSUE THREAD

**Issue by blunket** [nicolodavis/boardgame.io#345]
I have implemented some basic undo/redo buttons. However, Player 1's client is able to call undo during Player 2's turn, which is undoing player 2's moves.

**Comment by blunket** [comment]
Along with this issue, I want to add: it'd be pretty cool if the `ctx` var had a built-in way to check if undo/redo is even available. (right now I can just do that manually though)

**Comment by nicolodavis** [comment]
Thanks for the report! Will take a look.

**Comment by blunket** [comment]
Sounds good to me! I don't know how it would work in a game with multiple people able to move in the same turn -- didn't know that was possible. Wouldn't they just split it into different moves and switch the turn over to different players as necessary?

In any case, I think that'll probably be a fairly rare situation and so that will be a good solution for now. Maybe someone can raise an issue again if needed.

Is there any possibility to add undo and redo to server side code without breaking changes? Or is that too unnecessary for now?

**Comment by nicolodavis** [comment]
What do you mean by undo / redo in server side code?

At the moment an Undo / Redo is triggered on the client (and it is verified by the server before the Undo is broadcast to other players).
