### ISSUE TITLE
Reset function has no effect in multiplayer

### ISSUE THREAD

**Issue by blunket** [nicolodavis/boardgame.io#349]
Me again 😊 I tried implementing a reset button to appear on the client when the game was finished. It seems the reset function has no effect. It just says "connecting" forever, until you refresh the page. And then doesn't reset anything.

It seems like the game reset function would be on the server side. Maybe enabled for client calls but opt-out? (like the endGame function)

It is working fine in single player games. Not multiplayer.

**Comment by nicolodavis** [comment]
Yep, there is no way to reset a multiplayer game. The intended usage is to use the lobby to create a new game once the old one is done.

This can even be done in the same room with the same people based on the design at #354.  Does that solve your use-case?

**Comment by nicolodavis** [comment]
Until that is implemented, a poor man's workaround would be to implement a move that takes the game to the initial state (but you wouldn't be able to erase your game log using this; maybe that's even desirable depending on your game).

**Comment by blunket** [comment]
I see, thank you. For now I ended up generating a new game ID in the endGame call, and passing it to the view so both players have a rematch button linking to the same game.

I guess maybe cleaning up finished games would still be a useful thing though. Sort of like garbage collection, the finished game automatically resets after some time maybe? Just a thought for the future. :)

**Comment by somebody-vip** [comment]
I am encountering a similar issue. It would be wonderful if an naive game ‘reset’ function is added.
