### ISSUE TITLE
Error when persisting deltalog to Firebase RTDB

### ISSUE THREAD

**Issue by jorbascrumps** [nicolodavis/boardgame.io#362]
I haven't quite pinpointed where this is happening, but it seems that where ever `deltalog` is being prepared for storage it has `credentials` removed by setting them to `undefined`. Firebase does not accept `undefined` values, preferring `null` instead.

```
Error: Reference.set failed: First argument contains undefined in property 'GAME:ROOM.deltalog.1.action.payload.credentials'
```

Is the `credentials` field meant to be stored with an empty value or removed altogether? If the latter, I'd be happy to submit a PR removing all `undefined` values before saving to Firebase.

**Comment by nicolodavis** [comment]
It's meant to be removed. Thanks for noticing and volunteering to fix this.

**Comment by delucis** [comment]
I’m fairly certain this issue has been resolved — please feel free to re-open if you come across it again.
