### ISSUE TITLE
API Server running on PORT+1

### ISSUE THREAD

**Issue by barraponto** [nicolodavis/boardgame.io#364]
Docs are updated for the development version, but up to `0.31.1` (latest release) the API was different.
`server.run` used to take just a port number and run the api in `port+1`.
What should we do? It is really confusing as is.

**Comment by nicolodavis** [comment]
I should put out a release soon that should bring them back in sync. Sorry about that.

Long term I think we should stop committing to master and use a development branch, but I think it's ok to have this problem once in a while before v1.0.
