### ISSUE TITLE
Dealing with rounds and multiple stages of a turn with phases

### ISSUE THREAD

**Issue by MathieuLoutre** [nicolodavis/boardgame.io#367]
Hello,

I've just started using the framework and it's really been great to lay down the mechanics of the game, forcing me to think about the flow. 

The game I'm designing has a number of rounds at the end of which part of the game/player state is reset. Players also have a couple of phases of actions during their turn and can take multiple turns during a round (but only one turn at the time). So far, I've used "phases" to handle the round level stuff and do the reset but I'm reduced to a less declarative approach to restrict player's actions during their turn. Using phases to handle the player's turn instead feels like losing the round structure which is harder to reproduce in code.

What's a good way to handle this?

**Comment by nicolodavis** [comment]
Hey @MathieuLoutre. This has come up in the past and a proposal is being worked on to address exactly this: https://www.notion.so/Player-Phase-proposal-50d483a562db46c0a204d12c4c934f53

The idea is that we'll split Phases into Game Phases and Player Phases to take care of both ends. Game Phases handle round level stuff (inside which turns are played), and Player Phases are a way to break down an individual turn.

**Comment by MathieuLoutre** [comment]
That sounds spot on! I like the flexibility of the current thinking but running phases in parallel with only one type of phase feels a bit messy. Splitting them up feels right and still allows for flexible use. I'm not too familiar with the codebase yet but if I can help, I'd be happy to take a look.

**Comment by MathieuLoutre** [comment]
Just discovered that `endPhaseIf` is called before `endTurnIf` which means that `onPhaseEnd` is called first and the `endTurnIf` condition becomes the one from the next phase and not the current one. As a result, the player doesn't change.

I had to manually call `ctx.events.endPhase()` manually inside `onTurnBegin` to make sure the player moves on correctly. 

I suppose the current behaviour _could_ make sense given that phases can be used either inside a player's turn or as a game round/phase but when your proposition gets implemented, it would make sense to fix this.

**Comment by nicolodavis** [comment]
Yep, this will be fixed in the new proposal. We'd have "stages" inside turns and turns inside phases.

`onPhaseEnd` would happen after `onTurnEnd` / `endTurnIf`.

**Comment by MathieuLoutre** [comment]
Brilliant! For now, I've managed things somewhat manually and used a few tricks to keep things running how I want them. It's not ideal but it's far from bad!

**Comment by nicolodavis** [comment]
Closing this now that v0.33 is out.  Feel free to reopen if you find that the new release doesn't fix your problem.
