### ISSUE TITLE
[BUG] v0.31.0 Module not found: Can't resolve '@tweenjs/tween.js'

### ISSUE THREAD

**Issue by A1vinSmith** [nicolodavis/boardgame.io#373]
Really appreciate all contributor's work. I love boardgame too. I think we need to do some improvements in docs. I tried to understand the whole picture by reading documents at the beginning. But it doesn't provide too much help.
Like this one "Component Toolkit: Components for hex grids, cards, tokens." No clue about how to using UI Toolkit.
`import { Grid } from 'boardgame.io/ui'`
`import { HexGrid } from 'hex.js'`
`import { Token } from 'boardgame.io/ui/token'`
None of them worked.
Examples only have Chess and Tic-tac-toe are obviously not enough.
I don't even know an `import` in Chess examples.
`import Chess from 'chess.js';`
Which `chess.js`?

I also searched for some main contributor's repositories. None of them using hex-grid or any images.

I'm keen to help.

**Comment by nicolodavis** [comment]
Hey @A1vinSmith, the UI framework is deliberately not documented yet because it's still quite experimental and in flux.  Are there any other gaps in the documentation regarding how moves or phases work?

Can definitely use some help if you are keen to contribute to the UI framework or something else.

**Comment by A1vinSmith** [comment]
Okay, I'll try to make a demo using hex-grid board and image pieces. Then based on what I got there, create an example doc or do something for the UI reliable.

**Comment by A1vinSmith** [comment]
`import { HexGrid, Token } from 'boardgame.io/ui';`

Failed to compile
`./node_modules/boardgame.io/dist/ui.js`
`Module not found: Can't resolve '@tweenjs/tween.js' in '/Users/name/project/node_modules/boardgame.io/dist'`

Tried to add tween.js as dep, not worked anyway.

**Comment by A1vinSmith** [comment]
"boardgame.io": "0.30.0", working now.
so i guess something bad happened in v0.31.0 need to be fixed.

**Comment by flamecoals** [comment]
This issue is a duplicate of this one:

https://github.com/nicolodavis/boardgame.io/pull/358#issuecomment-467737406

Current workaround is to install the dependency

**Comment by A1vinSmith** [comment]
I've tried to add tween.js as a dependency, not worked anyway.
Then I give up to `import { * } from 'boardgame.io/ui'`
Btw, I found [react-hexgrid](https://github.com/hellenic/react-hexgrid) pretty good.

**Comment by flamecoals** [comment]
Did you try

npm install @tweenjs/tween.js --save

and it didn't work?

**Comment by A1vinSmith** [comment]
`npm install @tweenjs/tween.js --save` it's worked, thanks.
I think I tried the wrong deprecated name `tween.js`. This issue would be closed.

ps: ShardBound, Tavern Brawl tactics and BannerSaga Factions are all good games!

**Comment by shamseen** [comment]
hellooo - is there a way to use this in 0.43.3? i've installed tween and it's still not finding the ui module

**Comment by delucis** [comment]
The ui module was removed a few versions back. You can still find those old components here though: https://github.com/nicolodavis/bgio-react-component-toolkit
