### ISSUE TITLE
Hex component isn't tree-shakable and adds extra peer dependencies

### ISSUE THREAD

**Issue by d3dc** [nicolodavis/boardgame.io#385]
I have an entirely 2D game. When I import and use the `HexGrid`, I get compiler errors about being unable to resolve `three` and `@tweenjs/tween.js`.

The reason this is a problem for me is that I am developing in a mono-repo with a large number of packages. The compiler error gets thrown for every package at the same folder-level that imports the game's map.

This seems to have two causes:
1. [The way the Hex map component gets packaged always forces the 3D "stuff" to get included](https://github.com/nicolodavis/boardgame.io/blob/master/src/ui/hex.js#L14). The API is nice...

2. It also looks like the 3D UI code has undeclared peer dependencies; I guess this might be the easy way to solve the packaging/naming issue.

**Comment by flamecoals** [comment]
+1 had the same issue

@nicolodavis do you think it is okay if we package the 3D stuff in a separate package from the 2D stuff? I think webpack by default follows the requires() and I am not sure how to fix that

**Comment by d3dc** [comment]
Without really looking into it: Would `lazy` react components be an option here? (e.g. is `/packages` transpiled?)

**Comment by nicolodavis** [comment]
I'm open to splitting the two into separate packages, but it would be even better if we can keep them together for the API nicety.  Will take a look at lazy React components.

I think we just need to figure out an easy Webpack option to prevent it from following requires.

**Comment by nicolodavis** [comment]
The 3D components are now removed.  See #455 for context.

That should resolve this.  Feel free to re-open if it doesn't.
