### ISSUE TITLE
Create Room defaults to 2 players - even if the game does not support 2 players.

### ISSUE THREAD

**Issue by wmichaelshirk** [nicolodavis/boardgame.io#390]
If a game has, for example, between 3 and 5 players permitted - the select will show three - but the state still contains the value of 2 from its initialization in `create-room-form.js`.

**Comment by francoijs** [comment]
Thanks for reporting!
PR #392 shall fix it.

**Comment by nicolodavis** [comment]
Thanks for the quick fix!
