### ISSUE TITLE
can not start server.js

### ISSUE THREAD

**Issue by jacky-0000** [nicolodavis/boardgame.io#391]
I have install the esm package, and then I run "node -r esm src/server.js" ,this error is shown.

E:\website\board-game_v0.0.2>node -r esm src/server.js
E:\website\board-game_v0.0.2\node_modules\boardgame.io\dist\core.js:1
TypeError: Cannot read property 'name' of undefined
    at Object.Game (E:\website\board-game_v0.0.2\node_modules\boardgame.io\dist\core.js:2463:14)
    at Object.<anonymous> (E:\website\board-game_v0.0.2\src\game.js:10:43)
    at Generator.next (<anonymous>)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)

can anybody  help me?

**Comment by nicolodavis** [comment]
Can you post a link to your source so that someone can take a look?

**Comment by jacky-0000** [comment]
**src/server.js**

const Server = require('boardgame.io/server').Server;
const {TicTacToe} = require('./game');

const server = Server({
    games: [TicTacToe]
});
server.run(8000,()=>{
  console.log("Running server at http://127.0.0.1:8000")
});

**src/game.js**

/*
 * Copyright 2017 The boardgame.io Authors
 *
 * Use of this source code is governed by a MIT-style
 * license that can be found in the LICENSE file or at
 * https://opensource.org/licenses/MIT.
 */

//import { Game } from "boardgame.io/core";
const Game = require('boardgame.io/core').Game()

function IsVictory(cells) {
  const positions = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [0, 3, 6],
    [1, 4, 7],
    [2, 5, 8],
    [0, 4, 8],
    [2, 4, 6]
  ];

  for (let pos of positions) {
    const symbol = cells[pos[0]];
    let winner = symbol;
    for (let i of pos) {
      if (cells[i] != symbol) {
        winner = null;
        break;
      }
    }
    if (winner != null) return true;
  }

  return false;
}

const TicTacToe = Game({
  name: "ticTacToe",

  setup: () => ({
    cells: Array(9).fill(null)
  }),

  moves: {
    clickCell(G, ctx, id) {
      if (G.cells[id] === null) {
        G.cells[id] = ctx.currentPlayer;
      }
    }
  },

  flow: {
    movesPerTurn: 1,

    endGameIf: (G, ctx) => {
      if (IsVictory(G.cells)) {
        return { winner: ctx.currentPlayer };
      }
      if (G.cells.filter(c => c === null).length == 0) {
        return { draw: true };
      }
    }
  }
});

export default TicTacToe;

**Comment by nicolodavis** [comment]
You have a default export in game.js, but your import in server.js does not reflect that. Please take a look at the docs for how this is done.

Feel free to continue the conversation here if you still have problems.
