### ISSUE TITLE
Add optional depth parameter to simulate debug control?

### ISSUE THREAD

**Issue by nearwood** [nicolodavis/boardgame.io#419]
I'm implementing AI in a not-so-simple game that depends quite a bit on chance until later in the game. Simulating the beginning moves takes longer than I have patience for and is unnecessary. Would adding the depth as an optional argument to the simulate command in the debug panel be something you would be interested in?

Also, I wanted to mention that I really appreciate this library. It's made implementing a board game I enjoy super easy.

**Comment by nicolodavis** [comment]
Yes, allowing some knobs for the AI on the debug panel sounds like a great idea!

Also, take a look at the AI implementation. It's still a work in progress and not documented well, but there are ways to specify "objectives" that allow propagating scores from shallower states that might also help you.

**Comment by nearwood** [comment]
Ok, I have implemented a crude `iterations` argument to the simulate command. As I got more into the source code though I realized I mistook `Simulate` in `bot.js` (used just for tests as far as I can tell) with the simulate command which actually calls step for so many iterations.

It looks like for what I want to do, limit the depth, I just need to instantiate my own MCTSBot with the depth I want and use that instead of the default MCTSBot.

So, if modifying the `iterations` and `timeout` is something you'd be interested exposing in the debug panel then I could clean it up and make a PR? Or did you have something else in mind?

**Comment by nicolodavis** [comment]
I think exposing some generic options on the debug panel that are passed to the bot constructor would be great!

We just need to make sure that they're not specific to any one type of bot.

Maybe just an opaque JSON object that's sent to the constructor? We could also build a mechanism to automatically generate fields on the UI based on annotations in the bot's source code, but that's more complicated.

**Comment by delucis** [comment]
Closing as this was added in [v0.35.0](https://github.com/nicolodavis/boardgame.io/blob/master/docs/documentation/CHANGELOG.md#v0350).
