### ISSUE TITLE
Semaphore CI should run npm run lint

### ISSUE THREAD

**Issue by jasonharrison** [nicolodavis/boardgame.io#435]
It looks like some files made it into `master` that fail `npm run lint`.

![image](https://user-images.githubusercontent.com/304383/62751345-5e505e80-ba31-11e9-845a-472862b4743d.png)

I think we should have Semaphore CI run `npm run lint` and fail with a nonzero exit code.  [It seems that this needs to be done on Semaphore CI's website by a project owner](https://semaphoreci.com/docs/customizing-build-commands.html).

~~A PR to fix the lint errors will follow.~~ @nicolodavis beat me to it

**Comment by nicolodavis** [comment]
Thanks for the report Jason!  Yep, this is now fixed.
