### ISSUE TITLE
npm start broken on Windows

### ISSUE THREAD

**Issue by nicolodavis** [nicolodavis/boardgame.io#451]
https://github.com/nicolodavis/boardgame.io/blob/master/scripts/dev.sh
doesn't run on Windows and needs to be made platform agnostic.

On Linux / OSX you can do the following to run both client and server:

```js
npm install
npm start
```

Since dev.sh is broken on Windows you can't do this at the moment, although you can use the following manual workaround:

#### Run Client

```js
npm install
cd examples/react-web
npm install
npm start
```

#### Run Server

```js
npm install
npm run dev:server
```

**Comment by Stefan-Hanke** [comment]
@tsioap Refering to the PR - this is not only about the directory separator. I've just clone this repo, and `npm start` didn't work - because the `bash` command was not found (it is installed though). I'm not sure what scripting language to use for cross-platform purposes. Since NodeJS must be installed, maybe `dev.sh` could be converted to a JS script? Or maybe inline it completely into `package.json`?

**Comment by Stefan-Hanke** [comment]
As a sidenote, maybe a CI job running on windows could take care that some scenarios do not break to begin with.

**Comment by nicolodavis** [comment]
Yes, we'd have to make it a cross-platform script, similar to https://github.com/nicolodavis/boardgame.io/blob/master/scripts/clean.js

Welcome back @Stefan-Hanke!  Long time no see.

**Comment by tisoap** [comment]
Ah, I understand now. I did work for me because I use [Git Bash for Windows](https://gitforwindows.org/). I agree a Node script would be the best choice to make it cross platform regardless of terminal used, I'll look into converting it.

**Comment by nicolodavis** [comment]
Thanks @tisoap.  Feel free to update the existing PR or open a new one if you prefer.

**Comment by Stefan-Hanke** [comment]
@nicolodavis thanks - hope that I can contribute on a somewhat regular basis. Let's see how things are going.

**Comment by nicolodavis** [comment]
Your contributions are much appreciated.  As always, the current areas of focus are documented in the [roadmap](https://github.com/nicolodavis/boardgame.io/blob/master/roadmap.md).  The large ones are the ability to add bots to games, the game lobby and the Svelte migration.
