### ISSUE TITLE
All active players should be able to call events

### ISSUE THREAD

**Issue by delucis** [nicolodavis/boardgame.io#464]
As discussed in #458, now that active players and stages allow more complex multiplayer play within turns, it makes sense for any active player to be able to call an event (the stage-related events in particular) and not just the current player.

There are two parts:

- [x] Allow events to be called by any player in `activePlayers`
- [x] Expose `playerID` to the event handlers, so that `setStage` and `endStage` can operate on the player calling the event rather than always on the current player

I’d offer to tackle this, but I felt a little out of my depth reading the event and reducer logic, so it might be safer for someone who already understands how those work to make these changes.

**Comment by nicolodavis** [comment]
We'd also need to change `setActivePlayers` to operate on the player that called the event (`playerID`) rather that `currentPlayer`.

**Comment by nicolodavis** [comment]
After working on the documentation, I find that it's a bit confusing to have both `setStage` and `setActivePlayers`.  I think we should merge the functionality of `setActivePlayers` into `setStage`.

**Comment by nicolodavis** [comment]
Looks like all the features discussed here are now done.
