### ISSUE TITLE
retiring component toolkit

### ISSUE THREAD

**Issue by nicolodavis** [nicolodavis/boardgame.io#466]
Hey @flamecoals @chrisheninger @Korla ,

Just wanted to get your thoughts on this since I know that you guys use the React UI components.  The general consensus seems to be that people don't want a full fledged UI offering like #455 in the core library, and I'm not too keen on shipping a set of components that aren't well integrated either.

What would be the best way to retire the components without causing too much overhead for folks like you that want to continue using it?  Would just moving it to a separate repo suffice?  You can consume it directly from there (instead of via `boardgame.io/ui`, which is going away).

**Comment by jasonharrison** [comment]
I think retiring the components and moving them to a separate repo is a good idea.

**Comment by chrisheninger** [comment]
I never ended up using any of the components- just the client itself for all the state management. 🙂 

From a refactor point of view– dropping it into a separate repo and keeping all the imports/exports similar would probably be the least painful way to go about it– it would then just be a matter of updating your individual projects to fix where they're being pulled from.

**Comment by nicolodavis** [comment]
OK, the components are now at https://github.com/nicolodavis/bgio-react-component-toolkit.

**Comment by Korla** [comment]
This seems great, I mostly used the state management as well.
