### ISSUE TITLE
`gameMetadata` is undefined when using `Lobby`

### ISSUE THREAD

**Issue by haoyangnz** [nicolodavis/boardgame.io#467]
#436 seems to not have covered lobby.

**Comment by haoyangnz** [comment]
@jasonharrison Are you aware of this?

**Comment by jasonharrison** [comment]
@haoyangnz I was unaware.  Give me a few hours and I'll look into/fix.

**Comment by jasonharrison** [comment]
@haoyangnz Not sure if GitHub notifies you of related PRs, but https://github.com/nicolodavis/boardgame.io/pull/470 should fix this.

**Comment by haoyangnz** [comment]
@jasonharrison Amazing!
