### ISSUE TITLE
Support dynamic/changing number of iterations in MCTS bot 

### ISSUE THREAD

**Issue by jchadwick** [nicolodavis/boardgame.io#472]
When using the out-of-box MCTS in a game where the number of available moves (and therefore number of possible game states) declines as the game progresses, the time to calculate the best move reduces over time.

In other words: the _time_ to calculate _N_ `iterations` reduces as the `turn` count increases.

Currently, the `iterations` value is hard-coded when the bot is instantiated.  This should be updated to accept a function (much like the `objectives` function) that can return a dynamic number of iterations to support scenarios such as increasing the iteration count as the game progresses while the cost (in time) stays relatively flat.

The [AlphaBeta library](https://github.com/panchishin/alphabeta) offers [an alternative solution](https://github.com/panchishin/alphabeta#alphabetastepformilliseconds-milliseconds--callback-) which achieves the same effect of taking the same amount of time - running the algorithm for as many iterations as it can until the wall time expires - which also seems like a great option.

**Comment by nicolodavis** [comment]
Definitely open to the idea of having `iterations` accept a function in addition to an integer. Sounds like a great idea!

I'm probably not going to be able to get to this for a while, though.  Would you have time to make a PR for this?

**Comment by jchadwick** [comment]
Yes, I'd love to!

**Comment by nicolodavis** [comment]
Thanks a lot!  Let me know if you need pointers to the code or clarifications if anything is not clear.

**Comment by jchadwick** [comment]
Oh that sounds great, too!  I’ll look into it.

**Comment by jchadwick** [comment]
FYI, I only implemented the dynamic values and not the Debug Panel integration in this PR.  I've added a new issue (#476) to track the Debug Panel which I would like to do, too.

**Comment by jchadwick** [comment]
Oh, BTW, I included `playoutDepth`, too, because why the hell not. :)

**Comment by delucis** [comment]
Closing as this was added in [v0.35.0](https://github.com/nicolodavis/boardgame.io/blob/master/docs/documentation/CHANGELOG.md#v0350).
