### ISSUE TITLE
Consider re-ordering processing of setActivePlayers value argument

### ISSUE THREAD

**Issue by delucis** [nicolodavis/boardgame.io#488]
Currently arguments to `setActivePlayers` are processed in the following order:

1. `value`
2. `player`
3. `others`
4. `all`

[Source →](https://github.com/nicolodavis/boardgame.io/blob/e5fd40b16a961e026f451bf07fada6f2e1864ff8/src/core/turn-order.js#L63-L107)

This is “safe” in the sense that each argument that applies to a larger set of players follows the previous smaller argument, so if an `all` is passed, all players will definitely be in that stage. (And `others` and `player` are complementary.)

However, this order is not so convenient when using the `value` argument, because it prevents you combining `value` and other arguments. In particular for the following scenario:

```js
setActivePlayers({ all: 'A', value: { [id]: 'B' } })
```

Reading this, I would like to have all players in stage `A` _except_ for `id` who is in stage `B`. Kind of like a player–others set-up, but for an arbitrary player.

Given that `value` is in any case a more “advanced” use, I’d like to propose it being applied last inside `setActivePlayers` to allow for this kind of override behaviour. I’ll open a PR as it’s a super simple code change, but wanted to open this issue for a more thorough discussion.

**Comment by nicolodavis** [comment]
Sounds good to me.
