### ISSUE TITLE
[Enhancement] Subrepo for Server

### ISSUE THREAD

**Issue by ethanx94** [nicolodavis/boardgame.io#496]
I wanted to extend the server code with my own fork but it would be ideal if I could just fork the server by itself as a submodule. I know there was some talk of server enhancements recently. Would it be a good idea to split the server into its own separate repo?

**Comment by nicolodavis** [comment]
I'm open to splitting out the different components into separate repos eventually, but not at the moment.  I'd like to keep everything in one repo until we release v1.0.

What extension to the server are you planning?  Is there anything we can add to it that would prevent the need to fork it?

**Comment by ethanx94** [comment]
Probably quite a few things, right now in my app I just do and import and export of the server but no way to dig into the core. So the fork isn’t as much out of a specific enhancement rather than having some finer control to add more endpoints, etc.

There actually was one enhancement I was working on to simplify the game codes though. Our users just share these back and forth but I notice that some are generated with dashes and underscores which is a bit tedious to type.

**Comment by nicolodavis** [comment]
The Koa app is exposed to the user of the `Server` call, so you can add as many endpoints as you like without needing access to the library code.

**Comment by ethanx94** [comment]
That’s interesting. Though I’m not sure how to hook into the endpoints the server provides...how would someone go about adding a new GET route? Another property on the Server object? If I provide a route with the same name as a built in route could I override it completely?
![A21C7ECF-258D-4B08-98B1-0BBB441196C4](https://user-images.githubusercontent.com/4449468/67648484-2b20bb80-f90c-11e9-995a-2a5fff1b94c5.jpeg)
