### ISSUE TITLE
Understanding of concepts of phases | turns | stages

### ISSUE THREAD

**Issue by nicolasca** [nicolodavis/boardgame.io#497]
I have read the blog post about stages, the documentation, and looked some examples in the repo, and i'm quite sure I don't fully understand the way to use all this correctly.
Here is the flow of my game:

* Phase to draft a deck
  - player 1 and player 2 draft simulteanously
* Phase in game area
  - Army deployment
     + Player 1 deploys 1 unit
     + Player 2 deploys 1 unit
     *Repeat until it finishes*
  - Battle (this follows iterates 8 times. The battle itself has 8 times these four stages)
     + Pick used cards
        - Player 1 and 2 get back cards (simulteanously)
    + Set the orders
        - Player 1 and 2 set (simulteanously)
    + Use the orders
        - Player 1 uses one order
        - Player 2 uses one order
        *Repeat until no more orders*
    + Fight
        - Player 1 does one fight
        - Player 2 does one fight
        *Repeat until no more fight*

So obviously I'm not asking someone create the model for me :wink:
But I just try to show the complexity of the flow of the game.

Here what confuses me: it is written stages *represent phases inside turns*.
but here I feel that I have multiple turns inside one stage ! (for example when player 1 and 2 set orders alternately during the "Set the orders Stage"). 

What am I missing ? :smiley:

By the way, thanks for this library. I discovered it for few days, it looks great.

**Comment by nicolodavis** [comment]
It looks to me that all the periods in your game are phases.  Is there any difficulty that you had in applying the "phase" concept to your game?

I would probably do something like this:

```js
phases: {
  draft: { next: 'deployment' },
  deployment: { next: 'pick_used_cards' },
  pick_used_cards: { next: 'set_the_orders' },
  set_the_orders: { next: 'use_the_orders' },
  use_the_orders: { next: 'fight' },
  fight: { next: 'pick_used_cards' },
}
```

When the `fight` phase loops back, you can increment a `round` counter in `G` that can then be used to determine if you should bail out after the 8th time.

**Comment by nicolasca** [comment]
Ah all right.
Yes for me would be nice and clear to use this way, and I see that for now I don't need stages.
I didn't know if it could be correct (as a code pattern) to put everything "flat", as phases, and iterate only on some of them. But I think it fits very well in fact with the game flow.

Thanks for this clarification. 
And again, the library you developed is very cool. I will follow it closely !

**Comment by nicolodavis** [comment]
Glad to be of help.  Feel free to ask any questions you have have on our [Gitter](https://gitter.im/boardgame-io/General) channel or here.
