### ISSUE TITLE
Lint/Test errors

### ISSUE THREAD

**Issue by danielimmke** [nicolodavis/boardgame.io#501]
Hey Nicolo, I am trying to work on my branch but getting some errors after pulling master in.

boardgame.io/src/client/client.test.js
  17:10  error  'RandomBot' is defined but never used  no-unused-vars

And also:

● Validation Error:

  Module jest-transform-svelte in the transform option was not found.

When running Jest tests. I'm sure you would find these eventually but logging them just in case.

**Comment by nicolodavis** [comment]
Thanks!

The RandomBot error should be fixed.

I'm not sure the `jest-transform-svelte` thing is an actual problem.  My suspicion is that you haven't done an `npm install` after the dependency was added.  Can you re-run `npm install` and check if it works?

**Comment by danielimmke** [comment]
Yup - that was it. Thanks!
