### ISSUE TITLE
LobbyAPI requires refresh to see if another player has joined

### ISSUE THREAD

**Issue by sageguy09** [nicolodavis/boardgame.io#503]
Within a Lobby implementation, a user can create a game/room. Upon creation, the user is only able to see if another player has joined by refreshing the page.

Requesting that the default transport logic via socket.io include an update to allow updating of the create game/room line to reflect when another player has joined.

**Comment by sageguy09** [comment]
a potential alternative to this would be to allow users that create games, to be able to join the created room before another player has joined. This would require Lobby to support adding a `loading` option to `importedGames`

**Comment by nicolodavis** [comment]
I believe this is already captured in #354.  Please add to that issue if there is anything not captured there.
