### ISSUE TITLE
Events documentation vs implementation

### ISSUE THREAD

**Issue by delucis** [nicolodavis/boardgame.io#513]
The [Events documentation](https://boardgame.io/documentation/#/events) states that both `endStage` and `endPhase` can be passed `next` options to set which stage or phase will follow. However, if you look at how they are implemented, `EndStageEvent` and `EndPhaseEvent` don’t actually pass those arguments on:

https://github.com/nicolodavis/boardgame.io/blob/9d74966ad4656021c971b012e59973ebedcc618b/src/core/flow.js#L719-L721

https://github.com/nicolodavis/boardgame.io/blob/9d74966ad4656021c971b012e59973ebedcc618b/src/core/flow.js#L734-L738

`setStage` and `setPhase` are the events that will actually accomplish moving to a provided next value.

Should I update the docs to reflect the implementation, or should the implementation reflect what the docs currently say?

(I’m torn, because the `set` events are cleaner, but supporting `next` is consistent with `endTurn`.)

**Comment by nicolodavis** [comment]
Ah yes, I think we should update the documentation to remove references to `next` when it comes to `EndStage` and `EndPhase`.

**Comment by delucis** [comment]
Going to fix this, I realised the docs are actually referring to `next` options _in the game config_, which is correct… I’ll close this since I just misread it, but I’ll also see if there’s a way to improve it to avoid that confusion.
