### ISSUE TITLE
Server export difference in v0.34.x

### ISSUE THREAD

**Issue by nearwood** [nicolodavis/boardgame.io#518]
It looks like the exports were changed and maybe Server is not longer exported. Using this small example:

```
const Server = require('boardgame.io/server').Server;

const server = Server({
  games: [],
});

server.run(8000);
```
With:
* Node v13.1.0
* boardgame.io v0.34.2
* esm v3.2.25

Results in:

```
$ node -r esm server.js 
/home/nick/dev/tmp-boardgame.io/server.js:1
Error: Cannot find module 'boardgame.io/server'
Require stack:
- /home/nick/dev/tmp-boardgame.io/server.js
    at Object.<anonymous> (/home/nick/dev/tmp-boardgame.io/server.js:1)
    at Generator.next (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/nick/dev/tmp-boardgame.io/server.js' ]
}
```

It looks like it may not be exported anymore:

```
$ console.dir(require('boardgame.io));
{
  AI: [Function: AI],
  Client: [Function: Client],
  MCTSBot: [Function: MCTSBot],
  RandomBot: [Function: RandomBot],
  ReactClient: [Function: Client$1],
  ReactNativeClient: [Function: Client$2],
  TurnOrder: {
    DEFAULT: { first: [Function: first], next: [Function: next] },
    RESET: { first: [Function: first], next: [Function: next] },
    ONCE: { first: [Function: first], next: [Function: next] },
    CUSTOM: [Function: CUSTOM],
    CUSTOM_FROM: [Function: CUSTOM_FROM],
    SKIP: { first: [Function: first], next: [Function: next] }
  }
}
```

But I was able to find it at :
```
$ console.dir(require('boardgame.io/dist/server'));
{
  Firebase: [Function: Firebase],
  FlatFile: [Function: FlatFile],
  Mongo: [Function: Mongo],
  Server: [Function: Server]
}
```

So you can use `const Server = require('boardgame.io/dist/server').Server;` but that is weird. Advise on proper way to import it now?

**Comment by nicolodavis** [comment]
Ah, this is a bug because I forgot to consider `server.js` in https://github.com/nicolodavis/boardgame.io/blob/master/scripts/proxy-dirs.js

**Comment by nearwood** [comment]
Cool. Looks like I can just add it to subpackages.js? Easy first PR!

**Comment by nicolodavis** [comment]
Sure, feel free to send a PR.

It's not as simple as adding it to `subpackages.js` though.  The other subpackages are generated in `dist/esm` and `dist/cjs`.  What we do to wire them both is to generate a `package.json` file with a `module` and `main` field pointing to each.

So, we'd generate something like:
`client/package.json`
`core/package.json`
`ai/package.json`
...

at the top level.

The server package does not have an `esm` version.  So we'd need to generate a different `package.json` for it.  Simpler yet, we don't need to even generate a `package.json` for it but just a simple `server.js` at the top level that imports `./dist/server.js`.

We'd also need to add a `shell.rm` [here](https://github.com/nicolodavis/boardgame.io/blob/master/scripts/clean.js) to clean up the server related files at the top-level.  The way this whole thing works is that `proxy-dirs.js` is called right before the package is published (so we end up with these files at the top-level that can be imported as `boardgame.io/client` for example).  `clean.js` is run right after the package is published so these temporary files aren't kept around.

**Comment by nearwood** [comment]
Ok, I understand the submodule generation at at least a high level. But, it looks like Rollup is having issues with the typescript in the server module. I see there's a typescript plugin to convert it but something appears to be missing.

**Comment by nicolodavis** [comment]
But you are able to see dist/server.js and even import it in your client
code, so why do you think the typescript compilation isn't working?

**Comment by nearwood** [comment]
Yes, I was able to get it working on a packaged version from npm. Here, I am trying to build it locally to create a PR. I think I just figured it out though, just a matter of changing some filenames.

**Comment by nearwood** [comment]
Ok, created #519, let me know if it needs any changes.

**Comment by nicolodavis** [comment]
Thanks for the PR @nearwood!
