### ISSUE TITLE
Server location incorrect

### ISSUE THREAD

**Issue by MitchellJeppson** [nicolodavis/boardgame.io#522]
The doc import for server is:
    
    const Server = require('boardgame.io/server').Server;

 but this module does not exist. By contrast this line does work;
    
    const Server = require('boardgame.io/dist/server').Server;

Is this just a missed doc update or something larger?

**Comment by nicolodavis** [comment]
This was a bug that has been fixed and will be available in the next
release.  The docs are correct.
