### ISSUE TITLE
Multiplayer Client gives error "Type Error: multiplayer is not a function"

### ISSUE THREAD

**Issue by MitchellJeppson** [nicolodavis/boardgame.io#524]
If I create a Client with the multiplayer property set to `{ server: "http://localhost:8000" } ` I get the error above. If I set the multiplayer property to `SocketIO({server: "http://localhost:8000"}` it runs correctly. The docs show the former, is this just a doc issue or a bug?

**Comment by MitchellJeppson** [comment]
I should mention this was working before I upgraded to the newest version today.

**Comment by delucis** [comment]
This was changed in #502, so I think the issue is that the docs need updating.

**Comment by nicolodavis** [comment]
The docs are now updated.
