### ISSUE TITLE
pluginplayer test KO

### ISSUE THREAD

**Issue by vipher800** [nicolodavis/boardgame.io#530]
Your test (pluginplayer.test.js) is OK
```
const gametest = {
  playerSetup: () => ({ A: 1 }),
  plugins: [PluginPlayer],  
};
const TestClient = Client({ 
  game : gametest,
  debug: true,
  numPlayers: 2,
  multiplayer: Local()
 });
// eslint-disable-next-line
const App = () => (<TestClient playerID="0" />);
```

but with Phases, it seems that **G.players = {}**
```
const gametest = {
  playerSetup: () => ({ A: 1 }),
  plugins: [PluginPlayer],
  phases : {
    test : { start : true}
  }   
};
```

**Comment by filipelinhares** [comment]
I think the problem is here:
https://github.com/nicolodavis/boardgame.io/blob/b3e0bdcc7537ce318adcdc15628f206321a88ea0/src/plugins/plugin-player.js#L35-L36

`...G.players` must be the last:

```js
{
  [current]: G.player,
  ...G.players, 
}
```

**Comment by delucis** [comment]
Here is a minimal example reproducing the bug:

https://codesandbox.io/s/pluginplayer-with-phases-bug-2gw8c

When any phases are provided in the game configuration, the player plugin breaks.
