### ISSUE TITLE
Support objects in G by MCTS bot

### ISSUE THREAD

**Issue by michatrautweiler** [nicolodavis/boardgame.io#533]
While the random bot (and local multiplayer mode) supports JS objects in G, the MCTS bot does not seem to honor turn limits and legal moves anymore. See tictactoe sample with cells moved to class Model: 

```
const TicTacToe = {
  setup: () => ({
    log: ["start move recorder"],
    model: new Model(9)
  }),
```

[![Edit boardgame.io](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/boardgameio-zhvzl?fontsize=14&hidenavigation=1&theme=dark)

The moves made by a user (ids 5 and 2) and the random bot (id 7) are legal and show up in G.log. However, the single move made by the MCTS bot in turn 4 fills up all remaining cells at once (see model below). In addition, the MTCS bot does not seem to use the function "clickCell" to perform these actions as it does not execute line 49 ("G.log.unshift"):

```
{
  "log": [
    "p0, clickCell(2)",
    "p1, clickCell(7)",
    "p0, clickCell(5)",
    "start move recorder"
  ],
  "model": {
    "cells": [
      "1",
      "1",
      "0",
      "1",
      "1",
      "0",
      "1",
      "1",
      "0"
    ]
  }
}
```
This irregular move by the MCTS bot shows up in the visual "Log" tab as "clickCell(0)"
What am I missing?

**Comment by nicolodavis** [comment]
In general you should not be using classes (or functions) in your game state.  The game state needs to be a plain JSON object so that it can be serialized / deserialized. 

The MCTS implementation runs many simulations on the game state and probably overwrites the model since the same object is passed around by reference.
