### ISSUE TITLE
How to manipulate secret data in moves?

### ISSUE THREAD

**Issue by adngdb** [nicolodavis/boardgame.io#536]
I have a random deck of cards stored in the `secret` key of `G`. This is good because I don't want any players to be able to know what their next cards will be.

Now I want to give players a way to draw a card. My intuition was to do something like this: 

```js
moves: {
    drawCard: (G, ctx) => {
        const deck = G.secret.decks[ctx.currentPlayer];
        const hand = G.players[ctx.currentPlayer].hand;
        hand.push(deck.pop());
    },
}
```

However, this raises `TypeError: G.secret is undefined` when the move is called, which makes sense.

How can I solve this problem? Is there a way to run a move only on the server? 

Thanks!

*Side note: boardgame.io is amazing. Thanks for this excellent tool! :-)*

**Comment by nicolodavis** [comment]
Yes, you can set `optimistic = false` on the move (we should really rename this to something more intuitive).

```
moves: {
  drawCard: {
    move: (G, ctx) => { ... },
    optimistic: false,
  }
}
```

**Comment by adngdb** [comment]
Thank you! More than the name though, I wonder it is documented? I believe I have read the entire documentation and I don't think I have seen this mentioned. Did I just miss it?

**Comment by nicolodavis** [comment]
Ah, sorry about that.  Updated the docs.

**Comment by nicolodavis** [comment]
I've renamed the option to `client`, which will show up in the next release.

**Comment by adngdb** [comment]
Thank you! :heart:

**Comment by evandroabukamel** [comment]
Hello, everyone. I just found this question and I'm stuck with the same problem. I did declare my move on move section, but they are referenced too in stages section and I still receive the error `Cannot read property 'deck' of undefined` where I'm trying to access G.secret.deck inside a move. Can anyone help me, please? Thanks.

**Comment by delucis** [comment]
What does your move config look like?

Should be something like:

```js
const doSomething = {
  move: (G, ctx) => { /* use G.secret etc. */ },
  client: false,
}

const Game = {
  moves: { doSomething },

  turn: {
    stages: {
      stageA: {
        moves: { doSomething },
      },
    },
  },
}
```

If you have a reproduction you can share (repository or CodeSandbox for example), someone might be able to debug further.

**Comment by evandroabukamel** [comment]
Well, my moves are implemented in other files, and my configuration look like this. I wonder if this problem happens if I create a client that uses Socket.IO in another language, because my clients are going to be exclusive online, 

```javascript
// moves file
export function drawQuestionCard(G: GameState, ctx: any) {
  const newCard: Card = G.secret.questionsDeck.pop();
  G.players[ctx.currentPlayer].questionCard = { ...newCard };
}
```

```javascript
// game setup
moves: {
    drawQuestionCard: {
      move: drawQuestionCard,
      client: false,
    },
},
stages: {
      getQuestion: {
        moves: { drawQuestionCard },
      },
}
```

**Comment by delucis** [comment]
Ah, the `stages` field needs to be inside `turn`, but it looks like you have it at the top-level. It should be at `game.turn.stages` or `game.phases['phase'].turn.stages` to be read.

**Comment by evandroabukamel** [comment]
Oh, sorry, my stages are under the turn property, I omitted that:

```javascript
moves: { ... },
turn: { 
  ...,
  stages: {
    ...
  }
}
```

**Comment by delucis** [comment]
Ah, good! And now I’m seeing it, I think. In the top-level `moves` you use the long-form syntax with `client: false`, but not in `getQuestion.moves`. You have to use the long-form in both places.

I would probably do something like this in your moves file:

```js
export const drawQuestionCard = {
  move: (G: GameState, ctx: any) => {
    const newCard: Card = G.secret.questionsDeck.pop();
    G.players[ctx.currentPlayer].questionCard = { ...newCard };
  },
  client: false,
}
```

**Comment by evandroabukamel** [comment]
Hum, that might break my unit tests but I can fix that. I will give it a try, thanks, bro.
