### ISSUE TITLE
Multiplayer confusion

### ISSUE THREAD

**Issue by pociej** [nicolodavis/boardgame.io#537]
I have a feeling that `multiplayer` is not proper name of the field. Maybe i missed something but let me show the case. I have single player game, but i want game to be refresh resistant, so once browser is refreshed i see game in same state after refresh. Only way i see for this is to use `Client({ numPlayers : 1, multiplayer : { server : my_server_url }})`. May case is not a multiplayer at all but i have to make use of multiplayer. I feel that `server` would be better name maybe?

**Comment by nicolodavis** [comment]
I agree that this field can be confusing if not used in a true multiplayer game.  However, "multiplayer" is such an entrenched term in the video game community that I think it's better to keep it and document the fact that it just means "networked" rather than "more than one player".
