### ISSUE TITLE
secret state example does seem to do anything

### ISSUE THREAD

**Issue by amitport** [nicolodavis/boardgame.io#547]
this example doesn't seem to demonstrate anything as far as I can tell.

PS
thanks @nicolodavis for the fast responses. I guess you've noticed I'm going through the examples :) (I'm updating angular and boardgame.io version)

**Comment by nicolodavis** [comment]
Ah, it's actually just meant to show that each player sees a different slice of the state.  The button doesn't do anything (not sure how it goes there in the first place).  I've removed it now.

**Comment by nicolodavis** [comment]
Thanks for the reports.  Keep them coming!
