### ISSUE TITLE
Use bots as part of gameplay

### ISSUE THREAD

**Issue by br0p0p** [nicolodavis/boardgame.io#548]
I might just be missing it but is it possible to use a bot as a part of normal gameplay? For example, a human vs. AI chess game or blackjack where the dealer is a bot. From what I see, the bot is only available as a means to test gameplay and is not exposed through `ctx` or otherwise.

**Comment by nicolodavis** [comment]
You can as of v0.37.

This isn't documented yet, but the summary is that you can do something like:

```js
multiplayer: Local({ bots: ... })
```

Take a look at the unit tests in `src/client/transport/local.test.js` until the docs catch up.

**Comment by br0p0p** [comment]
Ah, great. For others who come across this, I found issue #383 which has some references to code for a similar use case. Thanks!

**Comment by dondragon2** [comment]
Any chance of the documentation updating any time soon to include this?

**Comment by koljakutschera** [comment]
> Any chance of the documentation updating any time soon to include this?

Any news on this one?
