### ISSUE TITLE
Problem with LocalMaster using previous instantiation of a Client

### ISSUE THREAD

**Issue by julienroulle** [nicolodavis/boardgame.io#552]
I've had some trouble with the Local use of the lib.

When I first instantiate a Local Game like that with bots coming from another screen:
```
bots = {'0': MyBot}
var GameApp = new Client({
        game: MyGame,
        board: MyBoard,
        multiplayer: new Local({
          bots,
        }),
      });
```
When going back to my "parameters screen" and changing the turn of my bot, meaning changing the following var:
```
bots: {'1': MyBot}
```

I discovered that my new GameApp will use the previous parameters of my 1st instantiation.

I managed to find the cause of the problem, but I'm not sure why this is causing a problem.
It comes from this [if-else statement](https://github.com/nicolodavis/boardgame.io/blob/9fc13f15af3b095fa6e57ccd2dd851477024ab86/src/client/transport/local.js#L213-L221).

By commenting out the first block of the if-statement, I managed to make it work as I wanted to be (meaning instantiating a new Local Master with my new given parameters). But as I am not really familiar with this part of the lib, I'm not sure what this if-statement is here for, and what damaged I could do by removing it.

Please share with me your knowledge about that if possible :)

**Comment by julienroulle** [comment]
Looks like commenting out this block breaks a test for Local Multiplayer without bots ..
So I don't know yet how to tackle this problem.

**Comment by julienroulle** [comment]
I managed it make it work by replacing the following:
```
const localMasters = new Map();
export function Local(opts) {
  return transportOpts => {
    let master;

    if (localMasters.has(transportOpts.gameKey)) {
      if (
        localMasters
          .get(transportOpts.gameKey)
          .storageAPI.games.has(transportOpts.gameID)
      ) {
        master = localMasters.get(transportOpts.gameKey);
      } else {
        master = new LocalMaster({
          game: transportOpts.game,
          bots: opts && opts.bots,
        });
        localMasters.set(transportOpts.gameKey, master);
      }
    } else {
      master = new LocalMaster({
        game: transportOpts.game,
        bots: opts && opts.bots,
      });
      localMasters.set(transportOpts.gameKey, master);
    }

    return new LocalTransport({ master, ...transportOpts });
  };
}
```

But for some reasons it makes the `multiplayer interactions` test of `client.test.js` fail ..

**Comment by julienroulle** [comment]
Doing this:
```
const localMasters = new Map();
export function Local(opts) {
  return transportOpts => {
    let master;

    if (localMasters.has(transportOpts.gameKey)) {
      if (!opts) {
        master = localMasters.get(transportOpts.gameKey);
      } else {
        master = new LocalMaster({
          game: transportOpts.game,
          bots: opts && opts.bots,
        });
        localMasters.set(transportOpts.gameKey, master);
      }
    } else {
      master = new LocalMaster({
        game: transportOpts.game,
        bots: opts && opts.bots,
      });
      localMasters.set(transportOpts.gameKey, master);
    }

    return new LocalTransport({ master, ...transportOpts });
  };
}
```
Also solves the problem, and makes the test pass. But i doubt it's an effective way to solve the problem ...
Please give me feedback on how I could investigate this issue further, I'm out of idea.

**Comment by nicolodavis** [comment]
That's a fine way to solve the problem (your last update).  Perhaps just consolidate the duplicated code in the two else branches.

Would you mind sending a PR for this?

**Comment by julienroulle** [comment]
Yes I was thinking about consolidating it as soon as I'd get feedback if I was on the right way or not!
I'll send you the PR later :)
Thanks for answering!
