### ISSUE TITLE
Unexpected behavior for setActivePlayers with plugins

### ISSUE THREAD

**Issue by pardahlman** [nicolodavis/boardgame.io#562]
Consider this very basic game:

```js
export const game = {
  turn: {
    onBegin: (G, ctx) =>
      ctx.events.setActivePlayers({
        currentPlayer: "firstStage",
        others: "secondStage"
      }),
    stages: {
      firstStage: {},
      secondStage: {}
    }
  }
};
```
The initial `ctx` is what I expect, the first player ends up in `firstStage` and the other in`secondStage.

```json
{
  "numPlayers": 2,
  "turn": 1,
  "currentPlayer": "0",
  "playOrder": [
    "0",
    "1"
  ],
  "playOrderPos": 0,
  "phase": null,
  "activePlayers": {
    "0": "firstStage",
    "1": "secondStage"
  },
  "numMoves": 0
}
```

I have written what I believe is a no-op plugin that just passes `G` without modifying it:

```js
export const examplePlugin = {
  fnWrap: (fn, game) => (G, ctx, ...args) => G
};
```

After adding the plugin to the game, the `ctx` has no active player - the entire property is `null`

```json
{
  "numPlayers": 2,
  "turn": 1,
  "currentPlayer": "0",
  "playOrder": [
    "0",
    "1"
  ],
  "playOrderPos": 0,
  "phase": null,
  "activePlayers": null,
  "numMoves": 0
}
```

Am I missing something?

**Comment by nicolodavis** [comment]
This appears to be a bug.

I revamped the plugin API quite a bit yesterday, so let me check if this bug is no longer with us after the rewrite.

**Comment by nicolodavis** [comment]
Ah, looks like you're not actually creating a no-op plugin (because you discard fn):

```js
fnWrap: (fn, game) => (G, ctx, ...args) => G
// should be either
fnWrap: fn => fn,
// or
fnWrap: fn => (G, ctx, ...args) => fn(G, ctx, ...args)
```

**Comment by nicolodavis** [comment]
https://codesandbox.io/s/wonderful-diffie-oo09t

**Comment by pardahlman** [comment]
Right, thanks for clarifying that 👌
