### ISSUE TITLE
phase endIf/onBegin timing

### ISSUE THREAD

**Issue by philihp** [nicolodavis/boardgame.io#569]
it seems during the update between 0.32 and 0.33, the timing of endIf and onBegin of phases has changed, such that when a phase begins, it checks `endIf` before running `onBegin`. Is this intentional?

**Comment by nicolodavis** [comment]
Yes, that is intentional.  `onBegin` only executes if the phase is "entered", but a phase is not entered if its `endIf` returns true.

So, you wouldn't be able to change the result of `endIf` via `onBegin`.  Is there a game scenario that's difficult to implement with this setup?

**Comment by philihp** [comment]
Perhaps... the scenario I want to implement is similar to in Agricola/Caverna, where:
* Each phase's ending is detected when all players' workers have been placed.
* Each phase begins by bringing all of a players' workers home.

This is adapted from my work on Fields of Arle, where I had a list of booleans for each player who had _pass_ed, and ended the phase when all players passed, and at the beginning of the phase I reset all the _pass_ booleans.

Maybe I could bring the workers home (or reset the _pass_ booleans) `onEnd`?

**Comment by delucis** [comment]
@philihp Could you check in your `endIf` if any moves have been made that turn? I think `numMoves` will be reset when `endIf` runs, but probably would be `1` or more when the phase is actually ending.

```js
{
  endIf: (G, ctx) => ctx.numMoves && G.allPassed
}
```

@nicolodavis Might this be an argument for a `beginIf` hook to split phase entry and exit logic and only run `endIf` when not entering a phase?

**Comment by nicolodavis** [comment]
I'd err on the side of fewer hooks unless absolutely necessary, although the symmetry of `beginIf / endIf` is nice.

@philihp Yeah, I would go with the booleans approach.  You could reset a `allWorkersPlaced` boolean in `onEnd`.  That way, you can still bring the workers back in `onBegin` and only use the boolean to trigger `endIf`.

**Comment by nicolodavis** [comment]
I'll close this because it resolves the immediate question on hand, but I don't mind continuing the discussing of whether a `beginIf` is necessary separately (if that leads to a cleaner design overall).
