### ISSUE TITLE
`ctx.events.endStage()` does not work

### ISSUE THREAD

**Issue by adngdb** [nicolodavis/boardgame.io#570]
Starting with version 0.38.1, calling `ctx.events.endStage()` in a move doesn't end the current stage. It works fine in version 0.38.0.

I don't have a good reproduction case as my code base is already quite complex, but I can work on one if it's not easy for you to reproduce.

**Comment by nicolodavis** [comment]
Hi @adngdb.  I'm not able to reproduce this.

Here is a CodeSandbox link demonstrating that the feature works: https://codesandbox.io/s/boardgameio-49w72

Can you try modifying it to demonstrate the problem that you observed?  It's most likely something that's incorrect in your game logic, but I'm not ruling out the possibility of a framework bug.

**Comment by adngdb** [comment]
Here's a reproduction of my issue: https://codesandbox.io/s/boardgameio-jfnj4

## Steps to reproduce

1. Click `Start Sequence`, player `0` gets into stage `act`.
2. Click `Pass`, player `1` gets into stage `act`.
3. Enable player 1 from the debug panel, then click `Pass`.

## Expected result

The `act` stage ends and players come back to being in no stage.

## Actual result

Player `1` stays in stage `act`, the game is blocked. Notice that the move is called, as `G.playersHavingPassed` keeps going up every time you click. However, `ctx.events.endStage()` has no effect.

**Comment by delucis** [comment]
Came up against this bug today too. Tried the CodeSandbox with v0.39.4, but it’s still broken. It’s curious because `setActivePlayers` works, but `endStage` doesn’t. I’ll keep investigating…

**Comment by delucis** [comment]
OK, now that 0.39.5 has been released I can confirm it fixes this issue 👍 

Here’s a fork of Adrian’s reproduction using 0.39.5:
https://codesandbox.io/s/boardgameio-1ohrt

**Comment by adngdb** [comment]
I confirm that version 0.39.5 solves my problem. Thanks a lot @delucis! :-)
