### ISSUE TITLE
TypeError: Cannot read property 'port' of null

### ISSUE THREAD

**Issue by ThatCheck** [nicolodavis/boardgame.io#584]
Hello, 

I use nest.js and I would like to add boardgame.io to it. But when I import the package and run `server.run(8000)`, I have the following error : 

 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of null. 

I think it's related to `async app.listen` in server.ts but I don't really know how to solve the issues currently. 

My code : 

```javascript
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import {Server} from 'boardgame.io/server';
import FuckTheDealer from './game/fuck-the-dealer';
import RedisIoAdapter from './live/RedisIOAdapter';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.useWebSocketAdapter(new RedisIoAdapter(app));
  app.enableCors({ credentials: true, origin: ["http://localhost:8000"] });
  await app.listen(3000);

  const server = Server({
    games : [FuckTheDealer]
  });
  const PORT = process.env.PORT || 3001;

  try {
    server.run(PORT, () => {
      console.log(`Serving at: http://localhost:${PORT}/`);
    });
  }catch(e){
    console.log("error", e);
  }


  if ((module as any).hot) {
    (module as any).hot.accept();
    (module as any).hot.dispose(
      () => {
        app.close();
        server.kill();
      }
    );
  }
}
bootstrap();

```

**Comment by delucis** [comment]
@ThatCheck Could you share a stack trace for that error? It would help in tracking down where exactly it’s happening.

**Comment by ThatCheck** [comment]
Oh sorry, I miss that. 

```
(node:18677) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of null
    at Object.run (/Users/floriancabirol/Projetcs/share-things/back/node_modules/boardgame.io/dist/server.js:4493:55)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by delucis** [comment]
I think this is actually related to these lines:

https://github.com/nicolodavis/boardgame.io/blob/167690c5db2b2bfa09e432439a7948c50049b77a/src/server/index.ts#L110

https://github.com/nicolodavis/boardgame.io/blob/167690c5db2b2bfa09e432439a7948c50049b77a/src/server/index.ts#L118

The [`address` method](https://nodejs.org/api/net.html#net_server_address) can potentially return `null` or a string, so there should probably be a check before reading `port` from it. In addition, although the server does `await server.listen()`, I don’t think `listen` actually returns a promise, it takes a callback, so `address` is being called potentially before the server has finished connecting, which might explain why it’s `null` for you.
