### ISSUE TITLE
Weird behavior when returning string from `order.first()`

### ISSUE THREAD

**Issue by janKir** [nicolodavis/boardgame.io#586]
I misunderstood the instructions on how to use the custom order functions and returned the playerID (a string) instead of the playOrder index (a number) from a phase's `order.first()` function.

```javascript
const phase = {
  moves: { ... },
  turn: {
    order: {
      first: (G) => G.firstPlayer
    }
  }
}
```

This also worked for the first move, and the correct player was set. This made it hard to detect where the upcoming unexpected behavior originated: When ending the first turn (and also phase), the second player was not the next player in playOrder as expected, but (in a 4 player game) was always either player "1" if the first player was player "0" or "2" or player "3" if the first player was player "1" or "3".

Despite the question why the app behaved like this, I would suggest making misuse of the `first()` function more clear or allow returning a string `playerID` with expected behavior.

**Comment by nicolodavis** [comment]
I agree.  We should probably log an error for cases like this.

**Comment by sarlow** [comment]
Thanks for bringing this up - I ran into the same issue as well. The unexpected behavior you mentioned comes from the way that the next player is calculated:

```javascript 
next: (G, ctx) => (ctx.playOrderPos + 1) % ctx.numPlayers
```

If playOrderPos is set to a string (e.g. "2"), then for a 4-player game:
```javascript
next: (G, ctx) => ("2"+ 1) % 4
next: (G, ctx) => (21) % 4
next: (G, ctx) => 1
```
I agree that an error message (or an additional note in the documentation) would be helpful.
