### ISSUE TITLE
Feature request: specify default move from a move list

### ISSUE THREAD

**Issue by sparr** [nicolodavis/boardgame.io#615]
Given a framework that forces a player to act, such as [this FBG feature request related to time limits](https://github.com/freeboardgames/FreeBoardGames.org/issues/494), a game needs to have a way to specify what the default action for a phase or stage is. This would often be some sort of "pass" action. My proposal here is that anywhere a move or move list can be specified, also accept a property specifying either a default move or a function with some logic for selecting a default move for a specific player.

**Comment by delucis** [comment]
Wouldn't it be better for the thing that “forces” action to say what it forces?

For example, in a case where a timeout does something, I would imagine it would be nice to have an `onTimeout` called which would advance game state rather than relying on a reference to a specific default move.

Are there use cases where this wouldn't be a good developer experience?

**Comment by sparr** [comment]
My thought is that there might be multiple use cases in the future for some universal default move for a particular game state, such as:

* player turn times out
* player chooses "do my default move in every phase/stage until I turn this option back off" to go AFK or similar
* player has quit the game, but the game rules do not allow players to drop out, so their position needs to perform a move at various future stages
* AI fails to choose a move
* game admin intentionally triggers a player's default move without having to figure out what that move should be
* ... ?? Something I haven't thought of yet.

While each of these could have their own handlers, I expect they would be relatively consistent across most game states, and so it would reduce duplication and effort if there was a single place to specify this move, and then only use event-specific handlers when one of those events needs to do something exceptional.

**Comment by delucis** [comment]
@sparr Thanks for the extra use case examples!

Would a pattern like the following work:

```js
function takeActionOne(G, ctx) {}
function takeActionTwo(G, ctx) {}

const game = {
  moves: {
    default: takeActionOne,
    takeActionOne,
    takeActionTwo,
  }

  phases: {
    A: {
      moves: {
        default: takeActionTwo,
        takeActionOne,
        takeActionTwo,
      }
    }
  }
}
```

For game implementers, the main difference between the default move and any other is presumably a reliable thing to call. Defining a default move like this works already, although you do need to remember to include `default` everywhere, but that would presumably also be the case for a different API.

I _think_ this would cover all your use cases above, do you agree? Using this approach might elevate the `default` move name to a special status once timers or another core part of the framework started relying on it, but for external uses (AFK, admin, other UI triggered calls) this seems like a good pattern to me.

**Comment by sparr** [comment]
This seems good. I suspect in many cases default would be a lambda that calls an existing action with specific parameters, rather than pointing directly at the action itself, but that still fits with your approach here.
