### ISSUE TITLE
UX issues with contenteditable editors in the debugger

### ISSUE THREAD

**Issue by will-hart** [nicolodavis/boardgame.io#618]
There are a few UX issues with the `contenteditable`s in the debug panel.

In particular hotkeys are still applied while a "move" argument is being edited. As a result of this, if you type an argument such as `abcd` then it will change tabs when the `b` key is pressed. This makes it impossible to type the input in.

Copying and pasting is also a bit challenging because `Ctrl+C` is captured and prevented.

Chrome 81, Win 10

**Comment by nicolodavis** [comment]
Thanks for the report @will-hart!

**Comment by nicolodavis** [comment]
@will-hart I was not able to reproduce the copy / paste issue.  Can you describe the issue you ran into?

**Comment by will-hart** [comment]
When I have an action in the debug view which has a `c` short cut, then trying to `ctrl+c` copy anywhere in the debugger triggers the `c` action and seems to `preventDefault` on the copy. Therefore `ctrl+c` doesn't work in the debug view.

I'm not really familiar with the code, but does https://github.com/nicolodavis/boardgame.io/blob/master/src/client/debug/main/Hotkey.svelte#L26 need to check for `e.altKey` or `e.ctrlKey` and ignore if they're pressed?
