### ISSUE TITLE
[Question] How can I know, from the lobby, if a game is over?

### ISSUE THREAD

**Issue by adngdb** [nicolodavis/boardgame.io#634]
Hi,

I haven't been able to find an answer to this question in the documentation or in the code. Is it even possible to know from outside a game client if the game is over? 

My use case is as follow: I'm building a 2 players game, and I want my "lobby" to be super simple: one button that, when clicked, makes you join a room and wait until that room has a second player, then loads the game. My problem is, once the game is over, I have no way from my custom lobby to know if the game is over.

I've seen in the default lobby that you always display an "Exit room" button, but I don't want to do that, as that breaks my UI, and sounds like a bad option to show. I instead would like to show a specific screen when a game is over, with the "exit room" button there (and only there). Is this possible right now with boardgame.io? 

Thanks!

**Comment by delucis** [comment]
Hey @adngdb — no, that’s not currently something updated in the game metadata, although it probably should be.
 
We already [read in game metadata](https://github.com/nicolodavis/boardgame.io/blob/5c12adb2fecbfb01c3ab7308441065aa331b46cd/src/master/master.ts#L175-L189) in the game master’s `onUpdate` method, so we could use that data to also write back to the metadata at [the same time we store the game state](https://github.com/nicolodavis/boardgame.io/blob/5c12adb2fecbfb01c3ab7308441065aa331b46cd/src/master/master.ts#L287-L291) if the gameover field of the game state is defined.
