### ISSUE TITLE
How to achieve another game

### ISSUE THREAD

**Issue by peacetrue** [nicolodavis/boardgame.io#643]
After the player has played a game, They want another game, Any good suggestions from **boardgame.io**?

**Comment by delucis** [comment]
@peacetrue Do you mean like a “Play Again” feature? If you’re using the Lobby API, you could either use the `create` and `join` endpoints to create a new game or use [the `playAgain` endpoint](https://github.com/nicolodavis/boardgame.io/blob/c51b277ccfde7578c5001bce6e8066e21912c428/src/server/api.ts#L235).

If you’re not using a server, you can use the `reset` method of the client to reset the game to the beginning state and let the player play again.

**Comment by peacetrue** [comment]
@delucis I will try the ``the playAgain endpoint.`` ,  It doesn't seem to be updated in the document.

**Comment by delucis** [comment]
@peacetrue Yes, create + join wouldn’t work so well for that use case but I think the `playAgain` endpoint might.

@flamecoals Are you still using the `playAgain` API? Would you be open to updating [the documentation](https://github.com/nicolodavis/boardgame.io/blob/master/docs/documentation/api/Lobby.md) to include it?

**Comment by peacetrue** [comment]
@flamecoals When my test is complete, I will update the document. In addition to the interface documentation, Lobby's example also needs to be updated synchronously.

**Comment by flamecoals** [comment]
Hey, yes, we still use it. I will send a PR soon with documentation

**Comment by peacetrue** [comment]
@delucis I made some attempts. 
First of all, the playAgain interface is used, it looks not much different from the create interface, but nextRoomId is useful.
After calling the playAgain interface, I want to see if the other player can receive the notification, but the result is no.
Finally, try to poll on the client, by determining whether GameMetadata contains nextRoomId, but the result is no.

I read the interface of GameMetadata:
```   
export interface GameMetadata {
    gameName: string;
    players: { [id: number]: PlayerMetadata };
    setupData: any;
    nextRoomID?: string;
  }
`` `
It seems that the current version has not been implemented.

Or my understanding is wrong, can you give me some suggestions?

**Comment by delucis** [comment]
@peacetrue Check out [the documentation @flamecoals just added](https://boardgame.io/documentation/#/api/Lobby?id=playing-again). You should get the `nextRoomId` as the response to a request to `playAgain.`

And you’re correct that this isn’t supported by the provided React Lobby component.

**Comment by delucis** [comment]
Going to close this now we have documentation. Let me know if you have any further questions.
