### ISSUE TITLE
[community] A place to talk about boardgame.io

### ISSUE THREAD

**Issue by adngdb** [nicolodavis/boardgame.io#660]
Hello,

I sometimes would like to be able to ask generic questions around boardgame.io without necessarily filing an issue — like, "can help make a new release?" :wink: or generic questions about usage, etc. 

As far as I know, there is no place dedicated to that. What would you think about opening one? That would probably help creating a sense of community, and would make it easier for folks to ask questions, figure out if boardgame.io is the right tool for their needs, and so on.

Regarding which tool to use, I'm a big fan of [Matrix](https://matrix.org/) / [Riot](https://about.riot.im/). Mozilla recently moved its community conversations from IRC to Matrix, the move went very well, we saw a lot of new contributors communicate, and it's given a great boost to the Matrix / Riot development teams.

Note that I'm mostly suggesting a chat platform, but a forum might be cool as well? 

Looking forward to your thoughts on this. :)

**Comment by nicolodavis** [comment]
Hi Adrian, thanks for your contributions to the project recently.  They are much appreciated.

About a forum / chat group, have you seen our [Gitter](https://gitter.im/boardgame-io/General) channel?  I've also floated the idea of potentially moving to [Discord](https://discordapp.com/), which  has a nicer mobile experience, but I do like the fact that Gitter chats are publicly readable without needing an account.

**Comment by adngdb** [comment]
Hah, no, I completely missed that! I see now that there's a small gitter icon in the readme. I guess it could be made a bit more obvious. I'll give that a go! (And might propose other changes to the readme too. )
