### ISSUE TITLE
Access PlayerPlugin from Client component

### ISSUE THREAD

**Issue by JGrzybowski** [nicolodavis/boardgame.io#668]
I use `PlayerPlugin` to store each of the players board state.
I need to show some of those data using components (eg. cards the player has in hand)

I noticed that `ctx` passed in props fro `Client` component is not a `CtxWithPlugins` that I would expect here. It would make some sense I guess, but how can `Client` get it's players data from `PlayerPlugin`?

**Comment by delucis** [comment]
You can access plugin data like this on the client (I’m assuming you’re using React):

```js
function Board ({ G, ctx, plugins }) {
  console.log(plugins.player.data);
  return null;
}
```

We still need to update this in the docs, which is being tracked in #594.

**Comment by JGrzybowski** [comment]
Thanks, it works! But isn't it a loophole for the cheating,  for client to have all PlayerPlugin data?

**Comment by delucis** [comment]
@JGrzybowski It could be yes, if you’re storing state that should be secret.

There’s no way currently for a plugin to specify secret state (like you can do with [`playerView`](https://boardgame.io/documentation/#/secret-state)), but it’s probably something that should be added.

**Comment by JGrzybowski** [comment]
Thanks, I guess that closes this question. But I will have to open another issue (for topics separation reasons) regarding storing those data in game Log.
