### ISSUE TITLE
endPhase ends turn

### ISSUE THREAD

**Issue by pociej** [nicolodavis/boardgame.io#676]
I just updated my game to newest version ( was 0.28 before ).  Game i single player, but i use multiplayer to be able to sync with server, however this issues appears with, `multiplayer : Local()` I see that every time i call endPhase also turn counter is increased. Is that expected behaviour and i dont understand something?

**Comment by delucis** [comment]
Yes, that’s expected behaviour as of v0.33.

This migration guide might help if you haven’t found it already: https://nicolodavis.com/blog/boardgame.io-0.33/

**Comment by pociej** [comment]
Oh great thx a lot @delucis
