### ISSUE TITLE
Add link to the next page in the documentation

### ISSUE THREAD

**Issue by Zhouzi** [nicolodavis/boardgame.io#683]
I am a new user so I am currently going through the documentation. When I was done reading the concepts, I wanted to jump to the next step but didn't find any pointers at the end of the page.

I would suggest adding a link to the next page at the bottom of the documentation's pages.

Let me know what you think, I would be happy to look into it and submit a PR if you are ok with that.

**Comment by delucis** [comment]
A PR for this would be great! The docs are built with docsify and maybe [this pagination plugin](https://github.com/imyelo/docsify-pagination) would work?

**Comment by Zhouzi** [comment]
Great, I'll have a look and submit a PR. Thanks for the link 👍
