### ISSUE TITLE
FlatFile save corruption "..does not look like a valid storage file ...FSReqCallback.readFileAfterClose "

### ISSUE THREAD

**Issue by jabza** [nicolodavis/boardgame.io#694]
Hi,

I'm using the FlatFile storage solution for bgio, and every so often a saved file will get corrupt giving the following error:
```
(node:12236) UnhandledPromiseRejectionWarning: Error: [node-persist][readFile] ...\.db\bgio\cccd562f198ed74bb9e75e8399330549 does not look like a valid storage file!
    at ...\node_modules\node-persist\src\local-storage.js:315:89
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
(node:12236) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

Upon inspecting the file, I can see it is no longer valid JSON. It looks like node-persist does not perform file-locking. Which, even though node is single-threaded, is still an issue. As it is possible for multiple asynchronous writes to occur. This is a limitation of node-persist, that exposes itself in high frequency scenarios.

I use node-persist for other data, and have worked around this error by queuing all writes and read via promise chaining. Perhaps BGIO should use a similar work around, or ditch node-persist?

Here is how I fixed the problem for my own node-persist based storage:

```
export class UserDB {
	constructor(dir) {
		this._db = storage.create({dir});
		this._db.init();

		this.requestQueue = Promise.resolve();
	}

	async getItem(key) {
		const getRequest = () => this._db.getItem(key);

		this.requestQueue = this.requestQueue.then(getRequest, getRequest);
		return this.requestQueue;
	}

	async setItem(key, value) {
		const setRequest = () => this._db.setItem(key, value);

		this.requestQueue = this.requestQueue.then(setRequest, setRequest);
		return this.requestQueue;
	}
}
```

This isn't a silver bullet though, so this error may still crop up.

**Comment by delucis** [comment]
Thanks for the report. This seems to be an instance of https://github.com/simonlast/node-persist/issues/108.

We’re not tied to `node-persist` if there’s a better option out there? Otherwise, if you think your changes improve things most of the time, perhaps we can patch the current implementation for now? Care to open a PR?

**Comment by jabza** [comment]
@delucis No problem, I've created the PR

**Comment by shashikanthgadgay** [comment]
@nicolodavis @delucis 
As the PR is merged, could you please do a release with these changes ?

Thanks
