### ISSUE TITLE
Current stage not accessible 

### ISSUE THREAD

**Issue by pociej** [nicolodavis/boardgame.io#697]
I used to use `phases` and now im trying to migrate to newest, i replaced phases by stages, but now im unable to read current stage. Phase field is presented in ctx object by stage is not. How then one can know what is current stage? I understand that moret han one player can be in given stage but its esential to be able to know if given player is in given stage when rendering game board.

**Comment by delucis** [comment]
This is available in `ctx.activePlayers`, which will either be `null` (no-one is in a stage) or a map of player IDs to stage names, e.g. `{ '1': 'stage-name' }`.

**Comment by pociej** [comment]
Problem is that it is always null. I see no way to have game setup that says what is start stage for player, and also even after manual call `events.setActivePlayers(['0'])` it stays null.

**Comment by delucis** [comment]
Where are you calling `setActivePlayers`? You can initialise the stages at the start of the turn using `turn.activePlayers` as described [here](https://boardgame.io/documentation/#/stages?id=configuring-active-players-at-the-beginning-of-a-turn).

**Comment by pociej** [comment]
Okay if setup `turn.activePlayers` like this i see what should be there btu still events dosnt work. I can call `setActivePlayers` or `endStage` nothing happened.
