### ISSUE TITLE
[API, Lobby] Standardize "room" and "game" terms to "match"

### ISSUE THREAD

**Issue by adngdb** [nicolodavis/boardgame.io#703]
As part of #665 we discovered that, in the Lobby and API, "rooms" where sometimes called "games". Upon discussing how to standardize that, we agreed that renaming to "match" was the correct move, as it makes more sense, and is also used in other similar tools.

This issue covers:
- removing all instances of `room`, `roomID`, `game` and `gameID` from the Lobby and API;
- replacing them with either `match` or `matchID`;
- updating the documentation to match (*pun intended*) these changes.

**Comment by adngdb** [comment]
(Feel free to assign me to this, I'll be working on it shortly. )

**Comment by adngdb** [comment]
PR: https://github.com/nicolodavis/boardgame.io/pull/704

**Comment by delucis** [comment]
Done in #704
