### ISSUE TITLE
In debug mode stage actions are not displayed

### ISSUE THREAD

**Issue by PiotrZakrzewski** [nicolodavis/boardgame.io#708]
# Steps to reproduce:
- define a stage with its own moves
- start in debug mode
- enter the stage
- the actions available in the debug menu are still from the main game object

I can fix this I think, if someone gives some hints and confirms that it is indeed a bug.

**Comment by delucis** [comment]
Hi — thanks for the report! Could you share a simple CodeSandbox or similar with the steps you describe? That would be helpful to double check this is a bug.

**Comment by PiotrZakrzewski** [comment]
Sure, here it goes:
https://codesandbox.io/s/boardgameio-issue-708-gipip

**Comment by delucis** [comment]
Thanks! The error is that `stages` has to be declared inside `turn`:

```diff
const TicTacToe = {
  setup: () => ({ cells: Array(9).fill(null) }),
+ turn: {
    stages: {
      stage1: {
        moves: { noop }
      }
    },
+ },
  moves: {
    clickCell: (G, ctx, id) => {
      ctx.events.setActivePlayers({ others: "stage1" });
    }
  }
};
```

If you add this it works. The debug options aren’t very sophisticated, so `noop` is shown even when not in the relevant stage.

**Comment by PiotrZakrzewski** [comment]
right! My bad, thanks.
