### ISSUE TITLE
server sync problem

### ISSUE THREAD

**Issue by pociej** [nicolodavis/boardgame.io#713]
Seems that there is problem with reconnection. Im running game with local server and sometimes completly randomly without any error runs only on current client, server has no info no move is played. Only way is to restart the server (client restart ends up with 'connecting...' loader in place of client) it is like 10% of cases. Game is pretty complex so i will need to create small repo for reproduction, but seems that multiplayer is broken.  Will provide more detail once i will track down way of data from client to server ( debuggin this library is not that simple thing) but smells like problem with socket disconnection and then reconnection.

**Comment by nicolodavis** [comment]
We use socket.io's internal mechanism for connects / reconnects.

Perhaps it is time to just use plain websockets for better control of this. Something like: https://stackoverflow.com/a/23176223

We could use https://github.com/websockets/ws on the server. We don't really use any of socket.io's higher level features like rooms / namespaces anyway.

**Comment by pociej** [comment]
@nicolodavis i doubt its fault of socket.io it very popular it works for sure. Here seems that multiplayer is simple broken.

**Comment by nicolodavis** [comment]
Let us know once you have more data that can be used to debug this.

**Comment by flamecoals** [comment]
Hey, we are experiencing the same issue in FBG, here is our issue:

https://github.com/freeboardgames/FreeBoardGames.org/issues/551

We can reliably reproduce it on our side, and I'm fairly confident it is a bgio issue. I wanted to look into it further in bgio side but I'm prioritizing other things for now

**Comment by nicolodavis** [comment]
The fix might be as simple as just re-issuing the "sync" command when a client goes out of sync. We don't do this currently.

**Comment by janKir** [comment]
We experience this too. Sometimes if a player has a slow/bad internet connection, the sync breaks and one has to refresh the page to fix it. Besides reconnecting automatically, it would be nice to have some kind of indicator if the game is currently synced or not in the client state, which we can display in the board.

**Comment by delucis** [comment]
@janKir You can use the `isConnected` prop to track if the player disconnects, which might be enough once we fix the reconnection logic.
