### ISSUE TITLE
state.plugins is undefined after restoring state from debug control panel

### ISSUE THREAD

**Issue by SmileyJames** [nicolodavis/boardgame.io#715]
Back again 😆 

To reproduce using tic-tac-toe example:
- Make some moves
- Save
- Restore
- Make another move

Causes TypeError: state.plugins is undefined

**Comment by SmileyJames** [comment]
So only G and ctx are saved, not the whole state
https://github.com/nicolodavis/boardgame.io/blob/master/src/client/debug/main/Controls.svelte#L9
Is there a reason for this? Can we save the whole state? Can we save plugins aswell as G and ctx.

**Comment by delucis** [comment]
Closed in #716
