### ISSUE TITLE
/playAgain only creating rooms with 2 players

### ISSUE THREAD

**Issue by binhrobles** [nicolodavis/boardgame.io#718]
When using the playAgain API, I'm only getting rooms created with 2 players, even when passing in IDs of games with 3 or 4 players.

Here's the flow I was attempting:
```
> curl localhost:8000/games/thirteen/qDXCwweaJ 
{"roomID":"qDXCwweaJ","players":[{"id":0,"name":"binh"},{"id":1,"name":"cedric"},{"id":2,"name":"malfoy"},{"id":3,"name":"postman"}]}

> curl --location --request POST 'http://localhost:8000/games/thirteen/qDXCwweaJ/playAgain' \
--header 'Content-Type: application/json' \
--data-raw '{
        "playerID": 2,
        "credentials": "d9jsG0W3R"
}'
{"nextRoomID":"vnD8uHCyW"}

> curl localhost:8000/games/thirteen/vnD8uHCyW
{"roomID":"vnD8uHCyW","players":[{"id":0},{"id":1}]}

> curl --location --request POST 'http://localhost:8000/games/thirteen/vnD8uHCyW/join' \
--header 'Content-Type: application/json' \
--data-raw '{
        "playerID": 3,
        "playerName": "postman"
}'
Player 3 not found
```

Am I missing something?

**Comment by delucis** [comment]
You need to pass in the number of players when making the `playAgain` request:

```sh
> curl --location --request POST 'http://localhost:8000/games/thirteen/qDXCwweaJ/playAgain' \
--header 'Content-Type: application/json' \
--data-raw '{
        "playerID": 2,
        "credentials": "d9jsG0W3R",
        "numPlayers": 3
}'
```

This isn’t super intuitive though — I would assume that `playAgain` should copy that from the previous game.

**Comment by binhrobles** [comment]
OK, yeah, makes sense. I made that assumption, and didn't see those options listed in the current Lobby API docs. 

I could probably spin a pull request together to make that the default behavior, allowing overrides, and update the docs, if you think that has value. Otherwise I can just update the doc and close this. LMK.

**Comment by delucis** [comment]
A PR would be great — and I think adding that default behaviour would be a good idea.

**Comment by delucis** [comment]
Done in #719.
