### ISSUE TITLE
Local(): Typescript error: "An argument for 'opts' was not provided."

### ISSUE THREAD

**Issue by janKir** [nicolodavis/boardgame.io#729]
After upgrading `boardgame.io` from 0.39.9 to 0.39.12, I get this typescript error when calling `Local()` without arguments: `local.d.ts(81, 31): An argument for 'opts' was not provided.`

[Looking into the source code](https://github.com/nicolodavis/boardgame.io/blob/0088cb5182cffda35da6bd3955f4fb81a942ae8f/src/client/transport/local.ts#L239), I guess that the `opts` just needs to be made optional. Also the function seems to check for undefined `opts` so nothing should break if the argument is not provided.

**Comment by delucis** [comment]
@janKir Thanks for spotting that — probably an oversight when I converted to Typescript. Would you be interested in putting together a PR to fix that?

**Comment by janKir** [comment]
@delucis sure I can do this!
