### ISSUE TITLE
How to mock the random plugin?

### ISSUE THREAD

**Issue by janKir** [nicolodavis/boardgame.io#730]
I currently use `lodash`s random and shuffle functions but want to switch to use the provided `random` plugin. However, can't figure out how to mock this plugin in my Jest scenario tests since it is provided as a function parameter and not imported as a module.

What is the recommended way to do this?

**Comment by delucis** [comment]
I think you could pass a replacement plugin in your game definition:

```js
const MockRandom = {
  name: 'random',
  api: () => {
    D6: (diceCount) => 3,
    Shuffle: (arr) => arr.reverse(),
  },
}

const game = {
  plugins: [MockRandom]
};
```

Haven’t tried this, but I don’t think boardgame.io does any checks to prevent you creating a plugin with the same name as an existing plugin, so this would overwrite the default random plugin. You could specify as many of the API methods as you needed (D4, Number, Die, etc…)

**Comment by janKir** [comment]
Thanks! I tried it and it seems to work like this:

```typescript
const dieMock = jest.fn();
dieMock.mockReturnValue(42);

const mockRandomPlugin = {
        name: "random",
        api: () => ({
          Die: dieMock,
          _obj: {
            getState: () => {},
            isUsed: () => false,
          },
        }),
      },
```

I also need to add the `getState` and `isUsed` functions in the `_obj` fields to prevent errors when boardgame.io tries to access those.

**Comment by delucis** [comment]
As of v0.49.9, we now provide a utility to help with this: https://boardgame.io/documentation/#/testing?id=override-random-api-since-v0499

**Comment by nukeop** [comment]
@delucis I tried this, I'm on `0.49.9`, but it looks like it's not exported correctly:

```typescript
import { MockRandom } from "boardgame.io/testing";
```

^ this fails

The exports in `dist/boardgameio.js` look like this:

```typescript
exports.Client = Client;
exports.Local = Local;
exports.MCTSBot = MCTSBot;
exports.RandomBot = RandomBot;
exports.ReactClient = Client$1;
exports.ReactNativeClient = Client$2;
exports.Simulate = Simulate;
exports.SocketIO = SocketIO;
exports.Step = Step;
exports.TurnOrder = TurnOrder;
```

Thanks for maintaining this very fun and easy to use library.

**Comment by delucis** [comment]
Ah, I think I forgot to include the `testing` directory, so 0.49.9 is missing `testing/package.json`: https://unpkg.com/browse/boardgame.io@0.49.9/

Should be a quick fix. Thanks for flagging it.

**Comment by delucis** [comment]
@nukeop Could you try 0.49.10 and see if that works for you?

**Comment by nukeop** [comment]
Thanks, it works now. Gotta be a world record in time to market...

**Comment by delucis** [comment]
If only everything was that easy to fix!
