### ISSUE TITLE
Postgres Storage Adapter

### ISSUE THREAD

**Issue by janKir** [nicolodavis/boardgame.io#736]
Just wanted to let you know that I implemented [a storage adapter for PostgreSQL](https://github.com/janKir/bgio-postgres) since we needed it for our project. It's working fine so far in our project but please let me know if you have any suggestions for improvements.

**Comment by delucis** [comment]
Nice! Feel free to add a link to your package here:

https://github.com/nicolodavis/boardgame.io/blob/7a58b1ee7000b09afbb3486576a9e64bbd2c98bd/docs/documentation/storage.md#L47-L50
