### ISSUE TITLE
"ReferenceError: regeneratorRuntime is not defined" after making the tutorial

### ISSUE THREAD

**Issue by Buzzele** [nicolodavis/boardgame.io#748]
Hi,

I am stuck. I did make the Tic Tac Toe tutorial but I dont get the Bot running. There comes up an Reference Error. I compared my code to CodeSandBox and there were a dev dependency for babel. I think that has to do with the error, but it did not fix my problem. Can anyone help me please?

**Comment by delucis** [comment]
Hi @Buzzele is this the React or the Plain JS tutorial?

[`regeneratorRuntime`](https://www.npmjs.com/package/regenerator-runtime) is a package that converts async functions for compatibility with old browsers, so it could be that your build is trying to do that for some reason, but not including the required module.

If you’re following the plain JS tutorial, you can explicitly declare that you don’t want to support old browsers with a browserslist field in `package.json`:

```json
"browserslist": "> 0.4% and not ie 11"
```

**Comment by Buzzele** [comment]
This works like a charm! Thank you. Perhaps this could be added to the tutorial? Just to be safe for beginners like me. Now I am eager to dive deeper in boardgame.io.
